services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: tastyigniter-app
    env_file:
      - ./.env
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
