<?php if ( ! defined('BASEPATH')) exit('No direct access allowed');

/**
 * Install the initial data structure for tables:
 *	countries, currencies, customer_groups, extensions,
 *  languages, layout_modules, layout_routes, layouts,
 *  mail_templates, mail_templates_data, pages, permalinks,
 *  permissions, security_questions, settings, staff_groups,
 *  statuses, uri_routes
 */

$insert_countries_data = "
  REPLACE INTO `".$this->db->dbprefix."countries` (`country_id`, `country_name`, `iso_code_2`, `iso_code_3`, `flag`, `format`, `status`) VALUES
  (1, 'Afghanistan', 'AF', 'AFG', 'data/flags/af.png', '', 1),
  (2, 'Albania', 'AL', 'ALB', 'data/flags/al.png', '', 1),
  (3, 'Algeria', 'DZ', 'DZA', 'data/flags/dz.png', '', 1),
  (4, 'American Samoa', 'AS', 'ASM', 'data/flags/as.png', '', 1),
  (5, 'Andorra', 'AD', 'AND', 'data/flags/ad.png', '', 1),
  (6, 'Angola', 'AO', 'AGO', 'data/flags/ao.png', '', 1),
  (7, 'Anguilla', 'AI', 'AIA', 'data/flags/ai.png', '', 1),
  (8, 'Antarctica', 'AQ', 'ATA', 'data/flags/aq.png', '', 1),
  (9, 'Antigua and Barbuda', 'AG', 'ATG', 'data/flags/ag.png', '', 1),
  (10, 'Argentina', 'AR', 'ARG', 'data/flags/ar.png', '', 1),
  (11, 'Armenia', 'AM', 'ARM', 'data/flags/am.png', '', 1),
  (12, 'Aruba', 'AW', 'ABW', 'data/flags/aw.png', '', 1),
  (13, 'Australia', 'AU', 'AUS', 'data/flags/au.png', '', 1),
  (14, 'Austria', 'AT', 'AUT', 'data/flags/at.png', '', 1),
  (15, 'Azerbaijan', 'AZ', 'AZE', 'data/flags/az.png', '', 1),
  (16, 'Bahamas', 'BS', 'BHS', 'data/flags/bs.png', '', 1),
  (17, 'Bahrain', 'BH', 'BHR', 'data/flags/bh.png', '', 1),
  (18, 'Bangladesh', 'BD', 'BGD', 'data/flags/bd.png', '', 1),
  (19, 'Barbados', 'BB', 'BRB', 'data/flags/bb.png', '', 1),
  (20, 'Belarus', 'BY', 'BLR', 'data/flags/by.png', '', 1),
  (21, 'Belgium', 'BE', 'BEL', 'data/flags/be.png', '', 1),
  (22, 'Belize', 'BZ', 'BLZ', 'data/flags/bz.png', '', 1),
  (23, 'Benin', 'BJ', 'BEN', 'data/flags/bj.png', '', 1),
  (24, 'Bermuda', 'BM', 'BMU', 'data/flags/bm.png', '', 1),
  (25, 'Bhutan', 'BT', 'BTN', 'data/flags/bt.png', '', 1),
  (26, 'Bolivia', 'BO', 'BOL', 'data/flags/bo.png', '', 1),
  (27, 'Bosnia and Herzegowina', 'BA', 'BIH', 'data/flags/ba.png', '', 1),
  (28, 'Botswana', 'BW', 'BWA', 'data/flags/bw.png', '', 1),
  (29, 'Bouvet Island', 'BV', 'BVT', 'data/flags/bv.png', '', 1),
  (30, 'Brazil', 'BR', 'BRA', 'data/flags/br.png', '', 1),
  (31, 'British Indian Ocean Territory', 'IO', 'IOT', 'data/flags/io.png', '', 1),
  (32, 'Brunei Darussalam', 'BN', 'BRN', 'data/flags/bn.png', '', 1),
  (33, 'Bulgaria', 'BG', 'BGR', 'data/flags/bg.png', '', 1),
  (34, 'Burkina Faso', 'BF', 'BFA', 'data/flags/bf.png', '', 1),
  (35, 'Burundi', 'BI', 'BDI', 'data/flags/bi.png', '', 1),
  (36, 'Cambodia', 'KH', 'KHM', 'data/flags/kh.png', '', 1),
  (37, 'Cameroon', 'CM', 'CMR', 'data/flags/cm.png', '', 1),
  (38, 'Canada', 'CA', 'CAN', 'data/flags/ca.png', '', 1),
  (39, 'Cape Verde', 'CV', 'CPV', 'data/flags/cv.png', '', 1),
  (40, 'Cayman Islands', 'KY', 'CYM', 'data/flags/ky.png', '', 1),
  (41, 'Central African Republic', 'CF', 'CAF', 'data/flags/cf.png', '', 1),
  (42, 'Chad', 'TD', 'TCD', 'data/flags/td.png', '', 1),
  (43, 'Chile', 'CL', 'CHL', 'data/flags/cl.png', '', 1),
  (44, 'China', 'CN', 'CHN', 'data/flags/cn.png', '', 1),
  (45, 'Christmas Island', 'CX', 'CXR', 'data/flags/cx.png', '', 1),
  (46, 'Cocos (Keeling) Islands', 'CC', 'CCK', 'data/flags/cc.png', '', 1),
  (47, 'Colombia', 'CO', 'COL', 'data/flags/co.png', '', 1),
  (48, 'Comoros', 'KM', 'COM', 'data/flags/km.png', '', 1),
  (49, 'Congo', 'CG', 'COG', 'data/flags/cg.png', '', 1),
  (50, 'Cook Islands', 'CK', 'COK', 'data/flags/ck.png', '', 1),
  (51, 'Costa Rica', 'CR', 'CRI', 'data/flags/cr.png', '', 1),
  (52, 'Cote D''Ivoire', 'CI', 'CIV', 'data/flags/ci.png', '', 1),
  (53, 'Croatia', 'HR', 'HRV', 'data/flags/hr.png', '', 1),
  (54, 'Cuba', 'CU', 'CUB', 'data/flags/cu.png', '', 1),
  (55, 'Cyprus', 'CY', 'CYP', 'data/flags/cy.png', '', 1),
  (56, 'Czech Republic', 'CZ', 'CZE', 'data/flags/cz.png', '', 1),
  (57, 'Denmark', 'DK', 'DNK', 'data/flags/dk.png', '', 1),
  (58, 'Djibouti', 'DJ', 'DJI', 'data/flags/dj.png', '', 1),
  (59, 'Dominica', 'DM', 'DMA', 'data/flags/dm.png', '', 1),
  (60, 'Dominican Republic', 'DO', 'DOM', 'data/flags/do.png', '', 1),
  (61, 'East Timor', 'TP', 'TMP', 'data/flags/tp.png', '', 1),
  (62, 'Ecuador', 'EC', 'ECU', 'data/flags/ec.png', '', 1),
  (63, 'Egypt', 'EG', 'EGY', 'data/flags/eg.png', '', 1),
  (64, 'El Salvador', 'SV', 'SLV', 'data/flags/sv.png', '', 1),
  (65, 'Equatorial Guinea', 'GQ', 'GNQ', 'data/flags/gq.png', '', 1),
  (66, 'Eritrea', 'ER', 'ERI', 'data/flags/er.png', '', 1),
  (67, 'Estonia', 'EE', 'EST', 'data/flags/ee.png', '', 1),
  (68, 'Ethiopia', 'ET', 'ETH', 'data/flags/et.png', '', 1),
  (69, 'Falkland Islands (Malvinas)', 'FK', 'FLK', 'data/flags/fk.png', '', 1),
  (70, 'Faroe Islands', 'FO', 'FRO', 'data/flags/fo.png', '', 1),
  (71, 'Fiji', 'FJ', 'FJI', 'data/flags/fj.png', '', 1),
  (72, 'Finland', 'FI', 'FIN', 'data/flags/fi.png', '', 1),
  (73, 'France', 'FR', 'FRA', 'data/flags/fr.png', '', 1),
  (74, 'France, Metropolitan', 'FX', 'FXX', 'data/flags/fx.png', '', 1),
  (75, 'French Guiana', 'GF', 'GUF', 'data/flags/gf.png', '', 1),
  (76, 'French Polynesia', 'PF', 'PYF', 'data/flags/pf.png', '', 1),
  (77, 'French Southern Territories', 'TF', 'ATF', 'data/flags/tf.png', '', 1),
  (78, 'Gabon', 'GA', 'GAB', 'data/flags/ga.png', '', 1),
  (79, 'Gambia', 'GM', 'GMB', 'data/flags/gm.png', '', 1),
  (80, 'Georgia', 'GE', 'GEO', 'data/flags/ge.png', '', 1),
  (81, 'Germany', 'DE', 'DEU', 'data/flags/de.png', '', 1),
  (82, 'Ghana', 'GH', 'GHA', 'data/flags/gh.png', '', 1),
  (83, 'Gibraltar', 'GI', 'GIB', 'data/flags/gi.png', '', 1),
  (84, 'Greece', 'GR', 'GRC', 'data/flags/gr.png', '', 1),
  (85, 'Greenland', 'GL', 'GRL', 'data/flags/gl.png', '', 1),
  (86, 'Grenada', 'GD', 'GRD', 'data/flags/gd.png', '', 1),
  (87, 'Guadeloupe', 'GP', 'GLP', 'data/flags/gp.png', '', 1),
  (88, 'Guam', 'GU', 'GUM', 'data/flags/gu.png', '', 1),
  (89, 'Guatemala', 'GT', 'GTM', 'data/flags/gt.png', '', 1),
  (90, 'Guinea', 'GN', 'GIN', 'data/flags/gn.png', '', 1),
  (91, 'Guinea-bissau', 'GW', 'GNB', 'data/flags/gw.png', '', 1),
  (92, 'Guyana', 'GY', 'GUY', 'data/flags/gy.png', '', 1),
  (93, 'Haiti', 'HT', 'HTI', 'data/flags/ht.png', '', 1),
  (94, 'Heard and Mc Donald Islands', 'HM', 'HMD', 'data/flags/hm.png', '', 1),
  (95, 'Honduras', 'HN', 'HND', 'data/flags/hn.png', '', 1),
  (96, 'Hong Kong', 'HK', 'HKG', 'data/flags/hk.png', '', 1),
  (97, 'Hungary', 'HU', 'HUN', 'data/flags/hu.png', '', 1),
  (98, 'Iceland', 'IS', 'ISL', 'data/flags/is.png', '', 1),
  (99, 'India', 'IN', 'IND', 'data/flags/in.png', '', 1),
  (100, 'Indonesia', 'ID', 'IDN', 'data/flags/id.png', '', 1),
  (101, 'Iran (Islamic Republic of)', 'IR', 'IRN', 'data/flags/ir.png', '', 1),
  (102, 'Iraq', 'IQ', 'IRQ', 'data/flags/iq.png', '', 1),
  (103, 'Ireland', 'IE', 'IRL', 'data/flags/ie.png', '', 1),
  (104, 'Israel', 'IL', 'ISR', 'data/flags/il.png', '', 1),
  (105, 'Italy', 'IT', 'ITA', 'data/flags/it.png', '', 1),
  (106, 'Jamaica', 'JM', 'JAM', 'data/flags/jm.png', '', 1),
  (107, 'Japan', 'JP', 'JPN', 'data/flags/jp.png', '', 1),
  (108, 'Jordan', 'JO', 'JOR', 'data/flags/jo.png', '', 1),
  (109, 'Kazakhstan', 'KZ', 'KAZ', 'data/flags/kz.png', '', 1),
  (110, 'Kenya', 'KE', 'KEN', 'data/flags/ke.png', '', 1),
  (111, 'Kiribati', 'KI', 'KIR', 'data/flags/ki.png', '', 1),
  (112, 'North Korea', 'KP', 'PRK', 'data/flags/kp.png', '', 1),
  (113, 'Korea, Republic of', 'KR', 'KOR', 'data/flags/kr.png', '', 1),
  (114, 'Kuwait', 'KW', 'KWT', 'data/flags/kw.png', '', 1),
  (115, 'Kyrgyzstan', 'KG', 'KGZ', 'data/flags/kg.png', '', 1),
  (116, 'Lao People''s Democratic Republic', 'LA', 'LAO', 'data/flags/la.png', '', 1),
  (117, 'Latvia', 'LV', 'LVA', 'data/flags/lv.png', '', 1),
  (118, 'Lebanon', 'LB', 'LBN', 'data/flags/lb.png', '', 1),
  (119, 'Lesotho', 'LS', 'LSO', 'data/flags/ls.png', '', 1),
  (120, 'Liberia', 'LR', 'LBR', 'data/flags/lr.png', '', 1),
  (121, 'Libyan Arab Jamahiriya', 'LY', 'LBY', 'data/flags/ly.png', '', 1),
  (122, 'Liechtenstein', 'LI', 'LIE', 'data/flags/li.png', '', 1),
  (123, 'Lithuania', 'LT', 'LTU', 'data/flags/lt.png', '', 1),
  (124, 'Luxembourg', 'LU', 'LUX', 'data/flags/lu.png', '', 1),
  (125, 'Macau', 'MO', 'MAC', 'data/flags/mo.png', '', 1),
  (126, 'FYROM', 'MK', 'MKD', 'data/flags/mk.png', '', 1),
  (127, 'Madagascar', 'MG', 'MDG', 'data/flags/mg.png', '', 1),
  (128, 'Malawi', 'MW', 'MWI', 'data/flags/mw.png', '', 1),
  (129, 'Malaysia', 'MY', 'MYS', 'data/flags/my.png', '', 1),
  (130, 'Maldives', 'MV', 'MDV', 'data/flags/mv.png', '', 1),
  (131, 'Mali', 'ML', 'MLI', 'data/flags/ml.png', '', 1),
  (132, 'Malta', 'MT', 'MLT', 'data/flags/mt.png', '', 1),
  (133, 'Marshall Islands', 'MH', 'MHL', 'data/flags/mh.png', '', 1),
  (134, 'Martinique', 'MQ', 'MTQ', 'data/flags/mq.png', '', 1),
  (135, 'Mauritania', 'MR', 'MRT', 'data/flags/mr.png', '', 1),
  (136, 'Mauritius', 'MU', 'MUS', 'data/flags/mu.png', '', 1),
  (137, 'Mayotte', 'YT', 'MYT', 'data/flags/yt.png', '', 1),
  (138, 'Mexico', 'MX', 'MEX', 'data/flags/mx.png', '', 1),
  (139, 'Micronesia, Federated States of', 'FM', 'FSM', 'data/flags/fm.png', '', 1),
  (140, 'Moldova, Republic of', 'MD', 'MDA', 'data/flags/md.png', '', 1),
  (141, 'Monaco', 'MC', 'MCO', 'data/flags/mc.png', '', 1),
  (142, 'Mongolia', 'MN', 'MNG', 'data/flags/mn.png', '', 1),
  (143, 'Montserrat', 'MS', 'MSR', 'data/flags/ms.png', '', 1),
  (144, 'Morocco', 'MA', 'MAR', 'data/flags/ma.png', '', 1),
  (145, 'Mozambique', 'MZ', 'MOZ', 'data/flags/mz.png', '', 1),
  (146, 'Myanmar', 'MM', 'MMR', 'data/flags/mm.png', '', 1),
  (147, 'Namibia', 'NA', 'NAM', 'data/flags/na.png', '', 1),
  (148, 'Nauru', 'NR', 'NRU', 'data/flags/nr.png', '', 1),
  (149, 'Nepal', 'NP', 'NPL', 'data/flags/np.png', '', 1),
  (150, 'Netherlands', 'NL', 'NLD', 'data/flags/nl.png', '', 1),
  (151, 'Netherlands Antilles', 'AN', 'ANT', 'data/flags/an.png', '', 1),
  (152, 'New Caledonia', 'NC', 'NCL', 'data/flags/nc.png', '', 1),
  (153, 'New Zealand', 'NZ', 'NZL', 'data/flags/nz.png', '', 1),
  (154, 'Nicaragua', 'NI', 'NIC', 'data/flags/ni.png', '', 1),
  (155, 'Niger', 'NE', 'NER', 'data/flags/ne.png', '', 1),
  (156, 'Nigeria', 'NG', 'NGA', 'data/flags/ng.png', '', 1),
  (157, 'Niue', 'NU', 'NIU', 'data/flags/nu.png', '', 1),
  (158, 'Norfolk Island', 'NF', 'NFK', 'data/flags/nf.png', '', 1),
  (159, 'Northern Mariana Islands', 'MP', 'MNP', 'data/flags/mp.png', '', 1),
  (160, 'Norway', 'NO', 'NOR', 'data/flags/no.png', '', 1),
  (161, 'Oman', 'OM', 'OMN', 'data/flags/om.png', '', 1),
  (162, 'Pakistan', 'PK', 'PAK', 'data/flags/pk.png', '', 1),
  (163, 'Palau', 'PW', 'PLW', 'data/flags/pw.png', '', 1),
  (164, 'Panama', 'PA', 'PAN', 'data/flags/pa.png', '', 1),
  (165, 'Papua New Guinea', 'PG', 'PNG', 'data/flags/pg.png', '', 1),
  (166, 'Paraguay', 'PY', 'PRY', 'data/flags/py.png', '', 1),
  (167, 'Peru', 'PE', 'PER', 'data/flags/pe.png', '', 1),
  (168, 'Philippines', 'PH', 'PHL', 'data/flags/ph.png', '', 1),
  (169, 'Pitcairn', 'PN', 'PCN', 'data/flags/pn.png', '', 1),
  (170, 'Poland', 'PL', 'POL', 'data/flags/pl.png', '', 1),
  (171, 'Portugal', 'PT', 'PRT', 'data/flags/pt.png', '', 1),
  (172, 'Puerto Rico', 'PR', 'PRI', 'data/flags/pr.png', '', 1),
  (173, 'Qatar', 'QA', 'QAT', 'data/flags/qa.png', '', 1),
  (174, 'Reunion', 'RE', 'REU', 'data/flags/re.png', '', 1),
  (175, 'Romania', 'RO', 'ROM', 'data/flags/ro.png', '', 1),
  (176, 'Russian Federation', 'RU', 'RUS', 'data/flags/ru.png', '', 1),
  (177, 'Rwanda', 'RW', 'RWA', 'data/flags/rw.png', '', 1),
  (178, 'Saint Kitts and Nevis', 'KN', 'KNA', 'data/flags/kn.png', '', 1),
  (179, 'Saint Lucia', 'LC', 'LCA', 'data/flags/lc.png', '', 1),
  (180, 'Saint Vincent and the Grenadines', 'VC', 'VCT', 'data/flags/vc.png', '', 1),
  (181, 'Samoa', 'WS', 'WSM', 'data/flags/ws.png', '', 1),
  (182, 'San Marino', 'SM', 'SMR', 'data/flags/sm.png', '', 1),
  (183, 'Sao Tome and Principe', 'ST', 'STP', 'data/flags/st.png', '', 1),
  (184, 'Saudi Arabia', 'SA', 'SAU', 'data/flags/sa.png', '', 1),
  (185, 'Senegal', 'SN', 'SEN', 'data/flags/sn.png', '', 1),
  (186, 'Seychelles', 'SC', 'SYC', 'data/flags/sc.png', '', 1),
  (187, 'Sierra Leone', 'SL', 'SLE', 'data/flags/sl.png', '', 1),
  (188, 'Singapore', 'SG', 'SGP', 'data/flags/sg.png', '', 1),
  (189, 'Slovak Republic', 'SK', 'SVK', 'data/flags/sk.png', '', 1),
  (190, 'Slovenia', 'SI', 'SVN', 'data/flags/si.png', '', 1),
  (191, 'Solomon Islands', 'SB', 'SLB', 'data/flags/sb.png', '', 1),
  (192, 'Somalia', 'SO', 'SOM', 'data/flags/so.png', '', 1),
  (193, 'South Africa', 'ZA', 'ZAF', 'data/flags/za.png', '', 1),
  (194, 'South Georgia &amp; South Sandwich Islands', 'GS', 'SGS', 'data/flags/gs.png', '', 1),
  (195, 'Spain', 'ES', 'ESP', 'data/flags/es.png', '', 1),
  (196, 'Sri Lanka', 'LK', 'LKA', 'data/flags/lk.png', '', 1),
  (197, 'St. Helena', 'SH', 'SHN', 'data/flags/sh.png', '', 1),
  (198, 'St. Pierre and Miquelon', 'PM', 'SPM', 'data/flags/pm.png', '', 1),
  (199, 'Sudan', 'SD', 'SDN', 'data/flags/sd.png', '', 1),
  (200, 'Suriname', 'SR', 'SUR', 'data/flags/sr.png', '', 1),
  (201, 'Svalbard and Jan Mayen Islands', 'SJ', 'SJM', 'data/flags/sj.png', '', 1),
  (202, 'Swaziland', 'SZ', 'SWZ', 'data/flags/sz.png', '', 1),
  (203, 'Sweden', 'SE', 'SWE', 'data/flags/se.png', '', 1),
  (204, 'Switzerland', 'CH', 'CHE', 'data/flags/ch.png', '', 1),
  (205, 'Syrian Arab Republic', 'SY', 'SYR', 'data/flags/sy.png', '', 1),
  (206, 'Taiwan', 'TW', 'TWN', 'data/flags/tw.png', '', 1),
  (207, 'Tajikistan', 'TJ', 'TJK', 'data/flags/tj.png', '', 1),
  (208, 'Tanzania, United Republic of', 'TZ', 'TZA', 'data/flags/tz.png', '', 1),
  (209, 'Thailand', 'TH', 'THA', 'data/flags/th.png', '', 1),
  (210, 'Togo', 'TG', 'TGO', 'data/flags/tg.png', '', 1),
  (211, 'Tokelau', 'TK', 'TKL', 'data/flags/tk.png', '', 1),
  (212, 'Tonga', 'TO', 'TON', 'data/flags/to.png', '', 1),
  (213, 'Trinidad and Tobago', 'TT', 'TTO', 'data/flags/tt.png', '', 1),
  (214, 'Tunisia', 'TN', 'TUN', 'data/flags/tn.png', '', 1),
  (215, 'Turkey', 'TR', 'TUR', 'data/flags/tr.png', '', 1),
  (216, 'Turkmenistan', 'TM', 'TKM', 'data/flags/tm.png', '', 1),
  (217, 'Turks and Caicos Islands', 'TC', 'TCA', 'data/flags/tc.png', '', 1),
  (218, 'Tuvalu', 'TV', 'TUV', 'data/flags/tv.png', '', 1),
  (219, 'Uganda', 'UG', 'UGA', 'data/flags/ug.png', '', 1),
  (220, 'Ukraine', 'UA', 'UKR', 'data/flags/ua.png', '', 1),
  (221, 'United Arab Emirates', 'AE', 'ARE', 'data/flags/ae.png', '', 1),
  (222, 'United Kingdom', 'GB', 'GBR', 'data/flags/gb.png', '{address_1}\n{address_2}\n{city} {postcode} {state}\n{country}', 1),
  (223, 'United States', 'US', 'USA', 'data/flags/us.png', '', 1),
  (224, 'United States Minor Outlying Islands', 'UM', 'UMI', 'data/flags/um.png', '', 1),
  (225, 'Uruguay', 'UY', 'URY', 'data/flags/uy.png', '', 1),
  (226, 'Uzbekistan', 'UZ', 'UZB', 'data/flags/uz.png', '', 1),
  (227, 'Vanuatu', 'VU', 'VUT', 'data/flags/vu.png', '', 1),
  (228, 'Vatican City State (Holy See)', 'VA', 'VAT', 'data/flags/va.png', '', 1),
  (229, 'Venezuela', 'VE', 'VEN', 'data/flags/ve.png', '', 1),
  (230, 'Viet Nam', 'VN', 'VNM', 'data/flags/vn.png', '', 1),
  (231, 'Virgin Islands (British)', 'VG', 'VGB', 'data/flags/vg.png', '', 1),
  (232, 'Virgin Islands (U.S.)', 'VI', 'VIR', 'data/flags/vi.png', '', 1),
  (233, 'Wallis and Futuna Islands', 'WF', 'WLF', 'data/flags/wf.png', '', 1),
  (234, 'Western Sahara', 'EH', 'ESH', 'data/flags/eh.png', '', 1),
  (235, 'Yemen', 'YE', 'YEM', 'data/flags/ye.png', '', 1),
  (236, 'Yugoslavia', 'YU', 'YUG', 'data/flags/yu.png', '', 1),
  (237, 'Democratic Republic of Congo', 'CD', 'COD', 'data/flags/cd.png', '', 1),
  (238, 'Zambia', 'ZM', 'ZMB', 'data/flags/zm.png', '', 1),
  (239, 'Zimbabwe', 'ZW', 'ZWE', 'data/flags/zw.png', '', 1);
";

$insert_currencies_data = "
  REPLACE INTO `".$this->db->dbprefix."currencies` (`currency_id`, `country_id`, `currency_name`, `currency_code`, `currency_symbol`, `iso_alpha2`, `iso_alpha3`, `iso_numeric`, `flag`, `currency_status`)
  VALUES
    (1, 1, 'Afghani', 'AFN', '؋', 'AF', 'AFG', 4, 'AF.png', 0),
    (2, 2, 'Lek', 'ALL', 'Lek', 'AL', 'ALB', 8, 'AL.png', 0),
    (3, 3, 'Dinar', 'DZD', 'د.ج', 'DZ', 'DZA', 12, 'DZ.png', 0),
    (4, 4, 'Dollar', 'USD', '$', 'AS', 'ASM', 16, 'AS.png', 0),
    (5, 5, 'Euro', 'EUR', '€', 'AD', 'AND', 20, 'AD.png', 0),
    (6, 6, 'Kwanza', 'AOA', 'Kz', 'AO', 'AGO', 24, 'AO.png', 0),
    (7, 7, 'Dollar', 'XCD', '$', 'AI', 'AIA', 660, 'AI.png', 0),
    (8, 8, 'Antarctican', 'AQD', 'A$', 'AQ', 'ATA', 10, 'AQ.png', 0),
    (9, 9, 'Dollar', 'XCD', '$', 'AG', 'ATG', 28, 'AG.png', 0),
    (10, 10, 'Peso', 'ARS', '$', 'AR', 'ARG', 32, 'AR.png', 0),
    (11, 11, 'Dram', 'AMD', 'դր.', 'AM', 'ARM', 51, 'AM.png', 0),
    (12, 12, 'Guilder', 'AWG', 'ƒ', 'AW', 'ABW', 533, 'AW.png', 0),
    (13, 13, 'Dollar', 'AUD', '$', 'AU', 'AUS', 36, 'AU.png', 1),
    (14, 14, 'Euro', 'EUR', '€', 'AT', 'AUT', 40, 'AT.png', 0),
    (15, 15, 'Manat', 'AZN', 'ман', 'AZ', 'AZE', 31, 'AZ.png', 0),
    (16, 16, 'Dollar', 'BSD', '$', 'BS', 'BHS', 44, 'BS.png', 0),
    (17, 17, 'Dinar', 'BHD', '.د.', 'BH', 'BHR', 48, 'BH.png', 0),
    (18, 18, 'Taka', 'BDT', '৳', 'BD', 'BGD', 50, 'BD.png', 0),
    (19, 19, 'Dollar', 'BBD', '$', 'BB', 'BRB', 52, 'BB.png', 0),
    (20, 20, 'Ruble', 'BYR', 'p.', 'BY', 'BLR', 112, 'BY.png', 0),
    (21, 21, 'Euro', 'EUR', '€', 'BE', 'BEL', 56, 'BE.png', 0),
    (22, 22, 'Dollar', 'BZD', 'BZ$', 'BZ', 'BLZ', 84, 'BZ.png', 0),
    (23, 23, 'Franc', 'XOF', '', 'BJ', 'BEN', 204, 'BJ.png', 0),
    (24, 24, 'Dollar', 'BMD', '$', 'BM', 'BMU', 60, 'BM.png', 0),
    (25, 25, 'Ngultrum', 'BTN', 'Nu.', 'BT', 'BTN', 64, 'BT.png', 0),
    (26, 26, 'Boliviano', 'BOB', '\$b', 'BO', 'BOL', 68, 'BO.png', 0),
    (27, 27, 'Marka', 'BAM', 'KM', 'BA', 'BIH', 70, 'BA.png', 0),
    (28, 28, 'Pula', 'BWP', 'P', 'BW', 'BWA', 72, 'BW.png', 0),
    (29, 29, 'Krone', 'NOK', 'kr', 'BV', 'BVT', 74, 'BV.png', 0),
    (30, 30, 'Real', 'BRL', 'R$', 'BR', 'BRA', 76, 'BR.png', 0),
    (31, 31, 'Dollar', 'USD', '$', 'IO', 'IOT', 86, 'IO.png', 0),
    (32, 231, 'Dollar', 'USD', '$', 'VG', 'VGB', 92, 'VG.png', 0),
    (33, 32, 'Dollar', 'BND', '$', 'BN', 'BRN', 96, 'BN.png', 0),
    (34, 33, 'Lev', 'BGN', 'лв', 'BG', 'BGR', 100, 'BG.png', 0),
    (35, 34, 'Franc', 'XOF', '', 'BF', 'BFA', 854, 'BF.png', 0),
    (36, 35, 'Franc', 'BIF', 'Fr', 'BI', 'BDI', 108, 'BI.png', 0),
    (37, 36, 'Riels', 'KHR', '៛', 'KH', 'KHM', 116, 'KH.png', 0),
    (38, 37, 'Franc', 'XAF', 'FCF', 'CM', 'CMR', 120, 'CM.png', 0),
    (39, 38, 'Dollar', 'CAD', '$', 'CA', 'CAN', 124, 'CA.png', 0),
    (40, 39, 'Escudo', 'CVE', '', 'CV', 'CPV', 132, 'CV.png', 0),
    (41, 40, 'Dollar', 'KYD', '$', 'KY', 'CYM', 136, 'KY.png', 0),
    (42, 41, 'Franc', 'XAF', 'FCF', 'CF', 'CAF', 140, 'CF.png', 0),
    (43, 42, 'Franc', 'XAF', '', 'TD', 'TCD', 148, 'TD.png', 0),
    (44, 43, 'Peso', 'CLP', '', 'CL', 'CHL', 152, 'CL.png', 0),
    (45, 44, 'Yuan Renminbi', 'CNY', '¥', 'CN', 'CHN', 156, 'CN.png', 0),
    (46, 45, 'Dollar', 'AUD', '$', 'CX', 'CXR', 162, 'CX.png', 0),
    (47, 46, 'Dollar', 'AUD', '$', 'CC', 'CCK', 166, 'CC.png', 0),
    (48, 47, 'Peso', 'COP', '$', 'CO', 'COL', 170, 'CO.png', 0),
    (49, 48, 'Franc', 'KMF', '', 'KM', 'COM', 174, 'KM.png', 0),
    (50, 50, 'Dollar', 'NZD', '$', 'CK', 'COK', 184, 'CK.png', 0),
    (51, 51, 'Colon', 'CRC', '₡', 'CR', 'CRI', 188, 'CR.png', 0),
    (52, 53, 'Kuna', 'HRK', 'kn', 'HR', 'HRV', 191, 'HR.png', 0),
    (53, 54, 'Peso', 'CUP', '₱', 'CU', 'CUB', 192, 'CU.png', 0),
    (54, 55, 'Pound', 'CYP', '', 'CY', 'CYP', 196, 'CY.png', 0),
    (55, 56, 'Koruna', 'CZK', 'Kč', 'CZ', 'CZE', 203, 'CZ.png', 0),
    (56, 49, 'Franc', 'CDF', 'FC', 'CD', 'COD', 180, 'CD.png', 0),
    (57, 57, 'Krone', 'DKK', 'kr', 'DK', 'DNK', 208, 'DK.png', 0),
    (58, 58, 'Franc', 'DJF', '', 'DJ', 'DJI', 262, 'DJ.png', 0),
    (59, 59, 'Dollar', 'XCD', '$', 'DM', 'DMA', 212, 'DM.png', 0),
    (60, 60, 'Peso', 'DOP', 'RD$', 'DO', 'DOM', 214, 'DO.png', 0),
    (61, 61, 'Dollar', 'USD', '$', 'TL', 'TLS', 626, 'TL.png', 0),
    (62, 62, 'Dollar', 'USD', '$', 'EC', 'ECU', 218, 'EC.png', 0),
    (63, 63, 'Pound', 'EGP', '£', 'EG', 'EGY', 818, 'EG.png', 0),
    (64, 64, 'Colone', 'SVC', '$', 'SV', 'SLV', 222, 'SV.png', 0),
    (65, 65, 'Franc', 'XAF', 'FCF', 'GQ', 'GNQ', 226, 'GQ.png', 0),
    (66, 66, 'Nakfa', 'ERN', 'Nfk', 'ER', 'ERI', 232, 'ER.png', 0),
    (67, 67, 'Kroon', 'EEK', 'kr', 'EE', 'EST', 233, 'EE.png', 0),
    (68, 68, 'Birr', 'ETB', '', 'ET', 'ETH', 231, 'ET.png', 0),
    (69, 69, 'Pound', 'FKP', '£', 'FK', 'FLK', 238, 'FK.png', 0),
    (70, 70, 'Krone', 'DKK', 'kr', 'FO', 'FRO', 234, 'FO.png', 0),
    (71, 71, 'Dollar', 'FJD', '$', 'FJ', 'FJI', 242, 'FJ.png', 0),
    (72, 72, 'Euro', 'EUR', '€', 'FI', 'FIN', 246, 'FI.png', 0),
    (73, 73, 'Euro', 'EUR', '€', 'FR', 'FRA', 250, 'FR.png', 0),
    (74, 75, 'Euro', 'EUR', '€', 'GF', 'GUF', 254, 'GF.png', 0),
    (75, 76, 'Franc', 'XPF', '', 'PF', 'PYF', 258, 'PF.png', 0),
    (76, 77, 'Euro  ', 'EUR', '€', 'TF', 'ATF', 260, 'TF.png', 0),
    (77, 78, 'Franc', 'XAF', 'FCF', 'GA', 'GAB', 266, 'GA.png', 0),
    (78, 79, 'Dalasi', 'GMD', 'D', 'GM', 'GMB', 270, 'GM.png', 0),
    (79, 80, 'Lari', 'GEL', '', 'GE', 'GEO', 268, 'GE.png', 0),
    (80, 81, 'Euro', 'EUR', '€', 'DE', 'DEU', 276, 'DE.png', 0),
    (81, 82, 'Cedi', 'GHC', '¢', 'GH', 'GHA', 288, 'GH.png', 0),
    (82, 83, 'Pound', 'GIP', '£', 'GI', 'GIB', 292, 'GI.png', 0),
    (83, 84, 'Euro', 'EUR', '€', 'GR', 'GRC', 300, 'GR.png', 0),
    (84, 85, 'Krone', 'DKK', 'kr', 'GL', 'GRL', 304, 'GL.png', 0),
    (85, 86, 'Dollar', 'XCD', '$', 'GD', 'GRD', 308, 'GD.png', 0),
    (86, 87, 'Euro', 'EUR', '€', 'GP', 'GLP', 312, 'GP.png', 0),
    (87, 88, 'Dollar', 'USD', '$', 'GU', 'GUM', 316, 'GU.png', 0),
    (88, 89, 'Quetzal', 'GTQ', 'Q', 'GT', 'GTM', 320, 'GT.png', 0),
    (89, 90, 'Franc', 'GNF', '', 'GN', 'GIN', 324, 'GN.png', 0),
    (90, 91, 'Franc', 'XOF', '', 'GW', 'GNB', 624, 'GW.png', 0),
    (91, 92, 'Dollar', 'GYD', '$', 'GY', 'GUY', 328, 'GY.png', 0),
    (92, 93, 'Gourde', 'HTG', 'G', 'HT', 'HTI', 332, 'HT.png', 0),
    (93, 94, 'Dollar', 'AUD', '$', 'HM', 'HMD', 334, 'HM.png', 0),
    (94, 95, 'Lempira', 'HNL', 'L', 'HN', 'HND', 340, 'HN.png', 0),
    (95, 96, 'Dollar', 'HKD', '$', 'HK', 'HKG', 344, 'HK.png', 0),
    (96, 97, 'Forint', 'HUF', 'Ft', 'HU', 'HUN', 348, 'HU.png', 0),
    (97, 98, 'Krona', 'ISK', 'kr', 'IS', 'ISL', 352, 'IS.png', 0),
    (98, 99, 'Rupee', 'INR', '₹', 'IN', 'IND', 356, 'IN.png', 0),
    (99, 100, 'Rupiah', 'IDR', 'Rp', 'ID', 'IDN', 360, 'ID.png', 0),
    (100, 101, 'Rial', 'IRR', '﷼', 'IR', 'IRN', 364, 'IR.png', 0),
    (101, 102, 'Dinar', 'IQD', '', 'IQ', 'IRQ', 368, 'IQ.png', 0),
    (102, 103, 'Euro', 'EUR', '€', 'IE', 'IRL', 372, 'IE.png', 0),
    (103, 104, 'Shekel', 'ILS', '₪', 'IL', 'ISR', 376, 'IL.png', 0),
    (104, 105, 'Euro', 'EUR', '€', 'IT', 'ITA', 380, 'IT.png', 0),
    (105, 52, 'Franc', 'XOF', '', 'CI', 'CIV', 384, 'CI.png', 0),
    (106, 106, 'Dollar', 'JMD', '$', 'JM', 'JAM', 388, 'JM.png', 0),
    (107, 107, 'Yen', 'JPY', '¥', 'JP', 'JPN', 392, 'JP.png', 0),
    (108, 108, 'Dinar', 'JOD', '', 'JO', 'JOR', 400, 'JO.png', 0),
    (109, 109, 'Tenge', 'KZT', 'лв', 'KZ', 'KAZ', 398, 'KZ.png', 0),
    (110, 110, 'Shilling', 'KES', '', 'KE', 'KEN', 404, 'KE.png', 0),
    (111, 111, 'Dollar', 'AUD', '$', 'KI', 'KIR', 296, 'KI.png', 0),
    (112, 114, 'Dinar', 'KWD', 'د.ك', 'KW', 'KWT', 414, 'KW.png', 0),
    (113, 115, 'Som', 'KGS', 'лв', 'KG', 'KGZ', 417, 'KG.png', 0),
    (114, 116, 'Kip', 'LAK', '₭', 'LA', 'LAO', 418, 'LA.png', 0),
    (115, 117, 'Lat', 'LVL', 'Ls', 'LV', 'LVA', 428, 'LV.png', 0),
    (116, 118, 'Pound', 'LBP', '£', 'LB', 'LBN', 422, 'LB.png', 0),
    (117, 119, 'Loti', 'LSL', 'L', 'LS', 'LSO', 426, 'LS.png', 0),
    (118, 120, 'Dollar', 'LRD', '$', 'LR', 'LBR', 430, 'LR.png', 0),
    (119, 121, 'Dinar', 'LYD', 'ل.د', 'LY', 'LBY', 434, 'LY.png', 0),
    (120, 122, 'Franc', 'CHF', 'CHF', 'LI', 'LIE', 438, 'LI.png', 0),
    (121, 123, 'Litas', 'LTL', 'Lt', 'LT', 'LTU', 440, 'LT.png', 0),
    (122, 124, 'Euro', 'EUR', '€', 'LU', 'LUX', 442, 'LU.png', 0),
    (123, 125, 'Pataca', 'MOP', 'MOP', 'MO', 'MAC', 446, 'MO.png', 0),
    (124, 140, 'Denar', 'MKD', 'ден', 'MK', 'MKD', 807, 'MK.png', 0),
    (125, 127, 'Ariary', 'MGA', 'Ar', 'MG', 'MDG', 450, 'MG.png', 0),
    (126, 128, 'Kwacha', 'MWK', 'MK', 'MW', 'MWI', 454, 'MW.png', 0),
    (127, 129, 'Ringgit', 'MYR', 'RM', 'MY', 'MYS', 458, 'MY.png', 0),
    (128, 130, 'Rufiyaa', 'MVR', 'Rf', 'MV', 'MDV', 462, 'MV.png', 0),
    (129, 131, 'Franc', 'XOF', 'MAF', 'ML', 'MLI', 466, 'ML.png', 0),
    (130, 132, 'Lira', 'MTL', 'Lm', 'MT', 'MLT', 470, 'MT.png', 0),
    (131, 133, 'Dollar', 'USD', '$', 'MH', 'MHL', 584, 'MH.png', 0),
    (132, 134, 'Euro', 'EUR', '€', 'MQ', 'MTQ', 474, 'MQ.png', 0),
    (133, 135, 'Ouguiya', 'MRO', 'UM', 'MR', 'MRT', 478, 'MR.png', 0),
    (134, 136, 'Rupee', 'MUR', '₨', 'MU', 'MUS', 480, 'MU.png', 0),
    (135, 137, 'Euro', 'EUR', '€', 'YT', 'MYT', 175, 'YT.png', 0),
    (136, 138, 'Peso', 'MXN', '$', 'MX', 'MEX', 484, 'MX.png', 0),
    (137, 139, 'Dollar', 'USD', '$', 'FM', 'FSM', 583, 'FM.png', 0),
    (138, 140, 'Leu', 'MDL', 'MDL', 'MD', 'MDA', 498, 'MD.png', 0),
    (139, 141, 'Euro', 'EUR', '€', 'MC', 'MCO', 492, 'MC.png', 0),
    (140, 142, 'Tugrik', 'MNT', '₮', 'MN', 'MNG', 496, 'MN.png', 0),
    (141, 143, 'Dollar', 'XCD', '$', 'MS', 'MSR', 500, 'MS.png', 0),
    (142, 144, 'Dirham', 'MAD', '', 'MA', 'MAR', 504, 'MA.png', 0),
    (143, 145, 'Meticail', 'MZN', 'MT', 'MZ', 'MOZ', 508, 'MZ.png', 0),
    (144, 146, 'Kyat', 'MMK', 'K', 'MM', 'MMR', 104, 'MM.png', 0),
    (145, 147, 'Dollar', 'NAD', '$', 'NA', 'NAM', 516, 'NA.png', 0),
    (146, 148, 'Dollar', 'AUD', '$', 'NR', 'NRU', 520, 'NR.png', 0),
    (147, 149, 'Rupee', 'NPR', '₨', 'NP', 'NPL', 524, 'NP.png', 0),
    (148, 150, 'Euro', 'EUR', '€', 'NL', 'NLD', 528, 'NL.png', 0),
    (149, 151, 'Guilder', 'ANG', 'ƒ', 'AN', 'ANT', 530, 'AN.png', 0),
    (150, 152, 'Franc', 'XPF', '', 'NC', 'NCL', 540, 'NC.png', 0),
    (151, 153, 'Dollar', 'NZD', '$', 'NZ', 'NZL', 554, 'NZ.png', 0),
    (152, 154, 'Cordoba', 'NIO', 'C$', 'NI', 'NIC', 558, 'NI.png', 0),
    (153, 155, 'Franc', 'XOF', '', 'NE', 'NER', 562, 'NE.png', 0),
    (154, 156, 'Naira', 'NGN', '₦', 'NG', 'NGA', 566, 'NG.png', 1),
    (155, 157, 'Dollar', 'NZD', '$', 'NU', 'NIU', 570, 'NU.png', 0),
    (156, 158, 'Dollar', 'AUD', '$', 'NF', 'NFK', 574, 'NF.png', 0),
    (157, 112, 'Won', 'KPW', '₩', 'KP', 'PRK', 408, 'KP.png', 0),
    (158, 159, 'Dollar', 'USD', '$', 'MP', 'MNP', 580, 'MP.png', 0),
    (159, 160, 'Krone', 'NOK', 'kr', 'NO', 'NOR', 578, 'NO.png', 0),
    (160, 161, 'Rial', 'OMR', '﷼', 'OM', 'OMN', 512, 'OM.png', 0),
    (161, 162, 'Rupee', 'PKR', '₨', 'PK', 'PAK', 586, 'PK.png', 0),
    (162, 163, 'Dollar', 'USD', '$', 'PW', 'PLW', 585, 'PW.png', 0),
    (163, 0, 'Shekel', 'ILS', '₪', 'PS', 'PSE', 275, 'PS.png', 0),
    (164, 164, 'Balboa', 'PAB', 'B/.', 'PA', 'PAN', 591, 'PA.png', 0),
    (165, 165, 'Kina', 'PGK', '', 'PG', 'PNG', 598, 'PG.png', 0),
    (166, 166, 'Guarani', 'PYG', 'Gs', 'PY', 'PRY', 600, 'PY.png', 0),
    (167, 167, 'Sol', 'PEN', 'S/.', 'PE', 'PER', 604, 'PE.png', 0),
    (168, 168, 'Peso', 'PHP', 'Php', 'PH', 'PHL', 608, 'PH.png', 0),
    (169, 169, 'Dollar', 'NZD', '$', 'PN', 'PCN', 612, 'PN.png', 0),
    (170, 170, 'Zloty', 'PLN', 'zł', 'PL', 'POL', 616, 'PL.png', 0),
    (171, 171, 'Euro', 'EUR', '€', 'PT', 'PRT', 620, 'PT.png', 0),
    (172, 172, 'Dollar', 'USD', '$', 'PR', 'PRI', 630, 'PR.png', 0),
    (173, 173, 'Rial', 'QAR', '﷼', 'QA', 'QAT', 634, 'QA.png', 0),
    (174, 49, 'Franc', 'XAF', 'FCF', 'CG', 'COG', 178, 'CG.png', 0),
    (175, 174, 'Euro', 'EUR', '€', 'RE', 'REU', 638, 'RE.png', 0),
    (176, 175, 'Leu', 'RON', 'lei', 'RO', 'ROU', 642, 'RO.png', 0),
    (177, 176, 'Ruble', 'RUB', 'руб', 'RU', 'RUS', 643, 'RU.png', 0),
    (178, 177, 'Franc', 'RWF', '', 'RW', 'RWA', 646, 'RW.png', 0),
    (179, 179, 'Pound', 'SHP', '£', 'SH', 'SHN', 654, 'SH.png', 0),
    (180, 178, 'Dollar', 'XCD', '$', 'KN', 'KNA', 659, 'KN.png', 0),
    (181, 179, 'Dollar', 'XCD', '$', 'LC', 'LCA', 662, 'LC.png', 0),
    (182, 180, 'Euro', 'EUR', '€', 'PM', 'SPM', 666, 'PM.png', 0),
    (183, 180, 'Dollar', 'XCD', '$', 'VC', 'VCT', 670, 'VC.png', 0),
    (184, 181, 'Tala', 'WST', 'WS$', 'WS', 'WSM', 882, 'WS.png', 0),
    (185, 182, 'Euro', 'EUR', '€', 'SM', 'SMR', 674, 'SM.png', 0),
    (186, 183, 'Dobra', 'STD', 'Db', 'ST', 'STP', 678, 'ST.png', 0),
    (187, 184, 'Rial', 'SAR', '﷼', 'SA', 'SAU', 682, 'SA.png', 0),
    (188, 185, 'Franc', 'XOF', '', 'SN', 'SEN', 686, 'SN.png', 0),
    (189, 142, 'Dinar', 'RSD', 'Дин', 'CS', 'SCG', 891, 'CS.png', 0),
    (190, 186, 'Rupee', 'SCR', '₨', 'SC', 'SYC', 690, 'SC.png', 0),
    (191, 187, 'Leone', 'SLL', 'Le', 'SL', 'SLE', 694, 'SL.png', 0),
    (192, 188, 'Dollar', 'SGD', '$', 'SG', 'SGP', 702, 'SG.png', 0),
    (193, 189, 'Koruna', 'SKK', 'Sk', 'SK', 'SVK', 703, 'SK.png', 0),
    (194, 190, 'Euro', 'EUR', '€', 'SI', 'SVN', 705, 'SI.png', 0),
    (195, 191, 'Dollar', 'SBD', '$', 'SB', 'SLB', 90, 'SB.png', 0),
    (196, 192, 'Shilling', 'SOS', 'S', 'SO', 'SOM', 706, 'SO.png', 0),
    (197, 193, 'Rand', 'ZAR', 'R', 'ZA', 'ZAF', 710, 'ZA.png', 0),
    (198, 113, 'Pound', 'GBP', '£', 'GS', 'SGS', 239, 'GS.png', 0),
    (199, 194, 'Won', 'KRW', '₩', 'KR', 'KOR', 410, 'KR.png', 0),
    (200, 195, 'Euro', 'EUR', '€', 'ES', 'ESP', 724, 'ES.png', 0),
    (201, 196, 'Rupee', 'LKR', '₨', 'LK', 'LKA', 144, 'LK.png', 0),
    (202, 199, 'Dinar', 'SDD', '', 'SD', 'SDN', 736, 'SD.png', 0),
    (203, 200, 'Dollar', 'SRD', '$', 'SR', 'SUR', 740, 'SR.png', 0),
    (204, 0, 'Krone', 'NOK', 'kr', 'SJ', 'SJM', 744, 'SJ.png', 0),
    (205, 202, 'Lilangeni', 'SZL', '', 'SZ', 'SWZ', 748, 'SZ.png', 0),
    (206, 203, 'Krona', 'SEK', 'kr', 'SE', 'SWE', 752, 'SE.png', 0),
    (207, 204, 'Franc', 'CHF', 'CHF', 'CH', 'CHE', 756, 'CH.png', 0),
    (208, 205, 'Pound', 'SYP', '£', 'SY', 'SYR', 760, 'SY.png', 0),
    (209, 206, 'Dollar', 'TWD', 'NT$', 'TW', 'TWN', 158, 'TW.png', 0),
    (210, 207, 'Somoni', 'TJS', '', 'TJ', 'TJK', 762, 'TJ.png', 0),
    (211, 208, 'Shilling', 'TZS', '', 'TZ', 'TZA', 834, 'TZ.png', 0),
    (212, 209, 'Baht', 'THB', '฿', 'TH', 'THA', 764, 'TH.png', 0),
    (213, 210, 'Franc', 'XOF', '', 'TG', 'TGO', 768, 'TG.png', 0),
    (214, 211, 'Dollar', 'NZD', '$', 'TK', 'TKL', 772, 'TK.png', 0),
    (215, 212, 'Pa\'anga', 'TOP', 'T$', 'TO', 'TON', 776, 'TO.png', 0),
    (216, 213, 'Dollar', 'TTD', 'TT$', 'TT', 'TTO', 780, 'TT.png', 0),
    (217, 214, 'Dinar', 'TND', '', 'TN', 'TUN', 788, 'TN.png', 0),
    (218, 215, 'Lira', 'TRY', 'YTL', 'TR', 'TUR', 792, 'TR.png', 0),
    (219, 216, 'Manat', 'TMM', 'm', 'TM', 'TKM', 795, 'TM.png', 0),
    (220, 217, 'Dollar', 'USD', '$', 'TC', 'TCA', 796, 'TC.png', 0),
    (221, 218, 'Dollar', 'AUD', '$', 'TV', 'TUV', 798, 'TV.png', 0),
    (222, 232, 'Dollar', 'USD', '$', 'VI', 'VIR', 850, 'VI.png', 0),
    (223, 219, 'Shilling', 'UGX', '', 'UG', 'UGA', 800, 'UG.png', 0),
    (224, 220, 'Hryvnia', 'UAH', '₴', 'UA', 'UKR', 804, 'UA.png', 0),
    (225, 221, 'Dirham', 'AED', '', 'AE', 'ARE', 784, 'AE.png', 0),
    (226, 222, 'Pound', 'GBP', '£', 'GB', 'GBR', 826, 'GB.png', 1),
    (227, 223, 'Dollar', 'USD', '$', 'US', 'USA', 840, 'US.png', 0),
    (228, 224, 'Dollar ', 'USD', '$', 'UM', 'UMI', 581, 'UM.png', 0),
    (229, 225, 'Peso', 'UYU', '\$U', 'UY', 'URY', 858, 'UY.png', 0),
    (230, 226, 'Som', 'UZS', 'лв', 'UZ', 'UZB', 860, 'UZ.png', 0),
    (231, 227, 'Vatu', 'VUV', 'Vt', 'VU', 'VUT', 548, 'VU.png', 0),
    (232, 228, 'Euro', 'EUR', '€', 'VA', 'VAT', 336, 'VA.png', 0),
    (233, 229, 'Bolivar', 'VEF', 'Bs', 'VE', 'VEN', 862, 'VE.png', 0),
    (234, 230, 'Dong', 'VND', '₫', 'VN', 'VNM', 704, 'VN.png', 0),
    (235, 233, 'Franc', 'XPF', '', 'WF', 'WLF', 876, 'WF.png', 0),
    (236, 234, 'Dirham', 'MAD', '', 'EH', 'ESH', 732, 'EH.png', 0),
    (237, 235, 'Rial', 'YER', '﷼', 'YE', 'YEM', 887, 'YE.png', 0),
    (238, 238, 'Kwacha', 'ZMK', 'ZK', 'ZM', 'ZMB', 894, 'ZM.png', 0),
    (239, 239, 'Dollar', 'ZWD', 'Z$', 'ZW', 'ZWE', 716, 'ZW.png', 0);
";

$insert_customer_groups_data = "
  REPLACE INTO `".$this->db->dbprefix."customer_groups` (`customer_group_id`, `group_name`, `description`, `approval`) VALUES
  (11, 'Default', '', 0);
";

$insert_extensions_data = "
  REPLACE INTO `".$this->db->dbprefix."extensions` (`extension_id`, `type`, `name`, `data`, `serialized`, `status`, `title`)
  VALUES
  (11, 'module', 'account_module', 'a:1:{s:7:\"layouts\";a:1:{i:0;a:4:{s:9:\"layout_id\";s:2:\"11\";s:8:\"position\";s:4:\"left\";s:8:\"priority\";s:1:\"1\";s:6:\"status\";s:1:\"1\";}}}', 1, 1, 'Account'),
  (12, 'module', 'local_module', 'a:3:{s:20:\"location_search_mode\";s:5:\"multi\";s:12:\"use_location\";s:1:\"0\";s:6:\"status\";s:1:\"1\";}', 1, 1, 'Local'),
  (13, 'module', 'categories_module', 'a:1:{s:7:\"layouts\";a:1:{i:0;a:4:{s:9:\"layout_id\";s:2:\"12\";s:8:\"position\";s:4:\"left\";s:8:\"priority\";s:1:\"1\";s:6:\"status\";s:1:\"1\";}}}', 1, 1, 'Categories'),
  (14, 'module', 'cart_module', 'a:3:{s:16:\"show_cart_images\";s:1:\"0\";s:13:\"cart_images_h\";s:0:\"\";s:13:\"cart_images_w\";s:0:\"\";}', 1, 1, 'Cart'),
  (15, 'module', 'reservation_module', 'a:1:{s:7:\"layouts\";a:1:{i:0;a:4:{s:9:\"layout_id\";s:2:\"16\";s:8:\"position\";s:4:\"left\";s:8:\"priority\";s:1:\"1\";s:6:\"status\";s:1:\"1\";}}}', 1, 1, 'Reservation'),
  (16, 'module', 'slideshow', 'a:6:{s:11:\"dimension_h\";s:3:\"420\";s:11:\"dimension_w\";s:4:\"1170\";s:6:\"effect\";s:4:\"fade\";s:5:\"speed\";s:3:\"500\";s:7:\"layouts\";a:1:{i:0;a:4:{s:9:\"layout_id\";s:2:\"15\";s:8:\"position\";s:3:\"top\";s:8:\"priority\";s:1:\"1\";s:6:\"status\";s:1:\"1\";}}s:6:\"slides\";a:3:{i:0;a:3:{s:4:\"name\";s:9:\"slide.png\";s:9:\"image_src\";s:14:\"data/slide.jpg\";s:7:\"caption\";s:0:\"\";}i:1;a:3:{s:4:\"name\";s:10:\"slide1.png\";s:9:\"image_src\";s:15:\"data/slide1.jpg\";s:7:\"caption\";s:0:\"\";}i:2;a:3:{s:4:\"name\";s:10:\"slide2.png\";s:9:\"image_src\";s:15:\"data/slide2.jpg\";s:7:\"caption\";s:0:\"\";}}}', 1, 1, 'Slideshow'),
  (18, 'payment', 'cod', 'a:5:{s:4:\"name\";N;s:11:\"order_total\";s:4:\"0.00\";s:12:\"order_status\";s:2:\"11\";s:8:\"priority\";s:1:\"1\";s:6:\"status\";s:1:\"1\";}', 1, 1, 'Cash On Delivery'),
  (20, 'module', 'pages_module', 'a:1:{s:7:\"layouts\";a:1:{i:0;a:4:{s:9:\"layout_id\";s:2:\"17\";s:8:\"position\";s:5:\"right\";s:8:\"priority\";s:1:\"1\";s:6:\"status\";s:1:\"1\";}}}', 1, 1, 'Pages'),
  (21, 'payment', 'paypal_express', 'a:11:{s:8:\"priority\";s:0:\"\";s:6:\"status\";s:1:\"0\";s:8:\"api_mode\";s:7:\"sandbox\";s:8:\"api_user\";s:0:\"\";s:8:\"api_pass\";s:0:\"\";s:13:\"api_signature\";s:0:\"\";s:10:\"api_action\";s:4:\"sale\";s:10:\"return_uri\";s:24:\"paypal_express/authorize\";s:10:\"cancel_uri\";s:21:\"paypal_express/cancel\";s:11:\"order_total\";s:4:\"0.00\";s:12:\"order_status\";s:2:\"11\";}', 1, 0, 'PayPal Express'),
  (23, 'theme', 'tastyigniter-orange', '', 1, 1, 'TastyIgniter Orange'),
  (24, 'theme', 'tastyigniter-blue', '', 1, 0, 'TastyIgniter Blue'),
  (25, 'module', 'banners_module', 'a:1:{s:7:\"banners\";a:1:{i:1;a:3:{s:9:\"banner_id\";s:1:\"1\";s:5:\"width\";s:0:\"\";s:6:\"height\";s:0:\"\";}}}', 1, 0, 'Banners');
";

$insert_languages_data = "
  REPLACE INTO `".$this->db->dbprefix."languages` (`language_id`, `code`, `name`, `image`, `directory`, `status`)
  VALUES
    (11, 'en', 'English', 'data/flags/gb.png', 'english', 1);
";

$insert_layout_modules_data = "
  REPLACE INTO `".$this->db->dbprefix."layout_modules` (`layout_module_id`, `layout_id`, `module_code`, `position`, `priority`, `status`) VALUES
    (60, 17, 'pages_module', 'content_right', 1, 1),
    (65, 11, 'slideshow', 'content_top', 1, 1),
    (66, 11, 'local_module', 'content_top', 2, 1),
    (67, 15, 'account_module', 'content_left', 1, 1),
    (68, 12, 'local_module', 'content_top', 1, 1),
    (69, 12, 'categories_module', 'content_left', 1, 1),
    (70, 12, 'cart_module', 'content_right', 1, 1),
    (71, 13, 'local_module', 'content_top', 1, 1),
    (72, 13, 'cart_module', 'content_right', 1, 1),
    (73, 16, 'reservation_module', 'content_top', 1, 1),
    (74, 18, 'local_module', 'content_top', 1, 1),
    (75, 18, 'categories_module', 'content_left', 1, 1),
    (76, 18, 'cart_module', 'content_right', 1, 1);
";

$insert_layout_routes_data = "
  REPLACE INTO `".$this->db->dbprefix."layout_routes` (`layout_route_id`, `layout_id`, `uri_route`) VALUES
    (19, 13, 'checkout'),
    (41, 16, 'reservation'),
    (44, 12, 'menus'),
    (59, 11, 'home'),
    (70, 18, 'local'),
    (71, 19, 'locations'),
    (72, 17, 'pages'),
    (100, 15, 'account/account'),
    (101, 15, 'account/details'),
    (102, 15, 'account/address'),
    (103, 15, 'account/orders'),
    (104, 15, 'account/reservations'),
    (105, 15, 'account/inbox'),
    (106, 15, 'account/reviews');
";

$insert_layouts_data = "
  REPLACE INTO `".$this->db->dbprefix."layouts` (`layout_id`, `name`) VALUES
    (11, 'Home'),
    (12, 'Menus'),
    (13, 'Checkout'),
    (15, 'Account'),
    (16, 'Reservation'),
    (17, 'Page'),
    (18, 'Local'),
    (19, 'Locations');
";

$insert_mail_templates_data = "
    REPLACE INTO `".$this->db->dbprefix."mail_templates` (`template_id`, `name`, `language_id`, `date_added`, `date_updated`, `status`) VALUES ('11', 'Default', '1', '2014-04-16 01:49:52', '2014-06-16 14:44:13', '1');
";

$insert_mail_templates_data_data = "
  REPLACE INTO `".$this->db->dbprefix."mail_templates_data` (`template_data_id`, `template_id`, `code`, `subject`, `body`, `date_added`, `date_updated`) VALUES
  (11, 11, 'registration', 'Account Created at {site_name}', '<p>Hello {first_name} {last_name},</p><p>Your account has now been created and you can log in using your email address and password by visiting our website or at the following URL: <a href=\"{login_link}\">Click Here</a></p><p>Thank you for using.<br /> {signature}</p>', '2014-04-16 00:56:00', '2014-05-15 15:24:56'),
  (12, 11, 'password_reset', 'Password Reset at {site_name}', '<p>Dear {first_name} {last_name},</p><p>Your password has been reset successfull! Please <a href=\"{login_link}\" target=\"_blank\">login</a> using your new password: {created_password}.</p><p>Thank you for using.<br /> {signature}</p>', '2014-04-16 00:56:00', '2014-05-15 15:46:30'),
  (13, 11, 'order', 'Order Successful - {order_number}', '<div><div class=\"text-align\"><p>Hello {first_name} {last_name},</p><p>Your order has been received and will be with you shortly.<br /><a href=\"{order_link}\">Click here</a> to view your order progress.<br /> Thanks for shopping with us online! &nbsp;</p><h3>Order Details</h3><p>Your order number is {order_number}<br /> This is a {order_type} order.<br /><strong>Order Date:</strong> {order_date}<br /><strong>Delivery Time</strong> {order_time}</p><h3>What you''ve ordered:</h3></div></div><table border=\"1\" cellspacing=\"1\" cellpadding=\"1\"><tbody><tr><td><div><div class=\"text-align\">{menus}</div></div></td><td><div><div class=\"text-align\">&nbsp;</div></div></td><td><div><div class=\"text-align\">&nbsp;</div></div></td><td><div><div class=\"text-align\">&nbsp;</div></div></td></tr><tr><td><div><div class=\"text-align\">{quantity}x</div></div></td><td><div><div class=\"text-align\"><p>{name}</p><p>{options}</p></div></div></td><td><div><div class=\"text-align\">{price}</div></div></td><td><div><div class=\"text-align\">{subtotal}</div></div></td></tr><tr><td><div><div class=\"text-align\">{/menus}</div></div></td><td><div><div class=\"text-align\">&nbsp;</div></div></td><td><div><div class=\"text-align\">&nbsp;</div></div></td><td><div><div class=\"text-align\">&nbsp;</div></div></td></tr></tbody></table><div><div class=\"text-align\"><p>&nbsp;</p><p>{order_totals}<br /><strong>{title}:</strong> {value}<br /> {/order_totals}</p><p>Your delivery address {order_address}</p><p>Your local restaurant {location_name}</p><p>We hope to see you again soon.</p><p>{signature}</p></div></div>', '2014-04-16 00:56:00', '2014-07-20 14:29:55'),
  (14, 11, 'reservation', 'Table Reserved - {reserve_number}', '<p>Hello {first_name} {last_name},<br /><br /> Your reservation at {location_name} has been booked for {reserve_guest} person(s) on {reserve_date} at {reserve_time}.</p><p>Thanks for reserving with us online!<br /><br /> We hope to see you again soon.<br /> {signature}</p>', '2014-04-16 00:56:00', '2014-07-22 20:13:48'),
  (15, 11, 'contact', 'Thanks for contacting us', '<h3><strong>Dear {full_name},</strong></h3><div><div>Topic: {contact_topic}.</div><div>Telephone: {contact_telephone}.</div></div><p>{contact_message}</p><p>Your {site_name} Team,</p><div>{signature}</div>', '2014-04-16 00:56:00', '2014-05-15 18:00:57'),
  (16, 11, 'internal', 'Subject here', '<p>Body here</p>', '2014-04-16 00:56:00', '2014-04-16 00:59:00'),
  (17, 11, 'order_alert', 'Subject here', '<p>Body here</p>', '2014-04-16 00:56:00', '2014-04-16 00:59:00'),
  (18, 11, 'reservation_alert', 'Subject here', '<p>Body here</p>', '2014-04-16 00:56:00', '2014-04-16 00:59:00');
";

$insert_pages_data = "
  REPLACE INTO `".$this->db->dbprefix."pages` (`page_id`, `language_id`, `name`, `title`, `heading`, `content`, `meta_description`, `meta_keywords`, `layout_id`, `navigation`, `date_added`, `date_updated`, `status`)
  VALUES
    (11, 11, 'About Us', 'About Us', 'About Us', '<h3 style=\"text-align: center;\"><span style=\"color: #993300;\">Aim</span></h3>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In venenatis massa ac magna sagittis, sit amet gravida metus gravida. Aenean dictum pellentesque erat, vitae adipiscing libero semper sit amet. Vestibulum nec nunc lorem. Duis vitae libero a libero hendrerit tincidunt in eu tellus. Aliquam consequat ultrices felis ut dictum. Nulla euismod felis a sem mattis ornare. Aliquam ut diam sit amet dolor iaculis molestie ac id nisl. Maecenas hendrerit convallis mi feugiat gravida. Quisque tincidunt, leo a posuere imperdiet, metus leo vestibulum orci, vel volutpat justo ligula id quam. Cras placerat tincidunt lorem eu interdum.</p>\r\n<h3 style=\"text-align: center;\"><span style=\"color: #993300;\">Mission</span></h3>\r\n<p>Ut eu pretium urna. In sed consectetur neque. In ornare odio erat, id ornare arcu euismod a. Ut dapibus sit amet erat commodo vestibulum. Praesent vitae lacus faucibus, rhoncus tortor et, bibendum justo. Etiam pharetra congue orci, eget aliquam orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eleifend justo eros, sit amet fermentum tellus ullamcorper quis. Cras cursus mi at imperdiet faucibus. Proin iaculis, felis vitae luctus venenatis, ante tortor porta nisi, et ornare magna metus sit amet enim. Phasellus et turpis nec metus aliquet adipiscing. Etiam at augue nec odio lacinia tincidunt. Suspendisse commodo commodo ipsum ac sollicitudin. Nunc nec consequat lacus. Donec gravida rhoncus justo sed elementum.</p>\r\n<h3 style=\"text-align: center;\"><span style=\"color: #a52a2a;\">Vision</span></h3>\r\n<p>Praesent erat massa, consequat a nulla et, eleifend facilisis risus. Nullam libero mi, bibendum id eleifend vitae, imperdiet a nulla. Fusce congue porta ultricies. Vivamus felis lectus, egestas at pretium vitae, posuere a nibh. Mauris lobortis urna nec rhoncus consectetur. Fusce sed placerat sem. Nulla venenatis elit risus, non auctor arcu lobortis eleifend. Ut aliquet vitae velit a faucibus. Suspendisse quis risus sit amet arcu varius malesuada. Vestibulum vitae massa consequat, euismod lorem a, euismod lacus. Duis sagittis dolor risus, ac vehicula mauris lacinia quis. Nulla facilisi. Duis tristique ipsum nec egestas auctor. Nullam in felis vel ligula dictum tincidunt nec a neque. Praesent in egestas elit.</p>', '', '', 17, 'a:2:{i:0;s:8:\"side_bar\";i:1;s:6:\"footer\";}', '2014-04-19 16:57:21', '2015-05-07 12:39:52', 1),
    (12, 11, 'Policy', 'Policy', 'Policy', '<div id=\"lipsum\">\r\n<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ligula eros, semper a lorem et, venenatis volutpat dolor. Pellentesque hendrerit lectus feugiat nulla cursus, quis dapibus dolor porttitor. Donec velit enim, adipiscing ac orci id, congue tincidunt arcu. Proin egestas nulla eget leo scelerisque, et semper diam ornare. Suspendisse potenti. Suspendisse vitae bibendum enim. Duis eu ligula hendrerit, lacinia felis in, mollis nisi. Sed gravida arcu in laoreet dictum. Nulla faucibus lectus a mollis dapibus. Fusce vehicula convallis urna, et congue nulla ultricies in. Nulla magna velit, bibendum eu odio et, euismod rhoncus sem. Nullam quis magna fermentum, ultricies neque nec, blandit neque. Etiam nec congue arcu. Curabitur sed tellus quam. Cras adipiscing odio odio, et porttitor dui suscipit eget. Aliquam non est commodo, elementum turpis at, pellentesque lorem.</p>\r\n<p>Duis nec diam diam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vulputate est et lorem sagittis, et mollis libero ultricies. Nunc ultrices tortor vel convallis varius. In dolor dolor, scelerisque ac faucibus ut, aliquet ac sem. Praesent consectetur lacus quis tristique posuere. Nulla sed ultricies odio. Cras tristique vulputate facilisis.</p>\r\n<p>Mauris at metus in magna condimentum gravida eu tincidunt urna. Praesent sodales vel mi eu condimentum. Suspendisse in luctus purus. Vestibulum dignissim, metus non luctus accumsan, odio ligula pharetra massa, in eleifend turpis risus in diam. Sed non lorem nibh. Nam at feugiat urna. Curabitur interdum, diam sit amet pulvinar blandit, mauris ante scelerisque nisi, sit amet placerat mi nunc eget orci. Nulla eget quam sit amet risus rhoncus lacinia a ut eros. Praesent non libero nisi. Mauris tincidunt at purus sit amet adipiscing. Donec interdum, velit nec dignissim vehicula, libero ipsum imperdiet ligula, lacinia mattis augue dui ac lacus. Aenean molestie sed nunc at pulvinar. Fusce ornare lacus non venenatis rhoncus.</p>\r\n<p>Aenean at enim luctus ante commodo consequat nec ut mi. Sed porta adipiscing tempus. Aliquam sit amet ullamcorper ipsum, id adipiscing quam. Fusce iaculis odio ut nisi convallis hendrerit. Morbi auctor adipiscing ligula, sit amet aliquet ante consectetur at. Donec vulputate neque eleifend libero pellentesque, vitae lacinia enim ornare. Vestibulum fermentum erat blandit, ultricies felis ac, facilisis augue. Nulla facilisis mi porttitor, interdum diam in, lobortis ipsum. In molestie quam nisl, lacinia convallis tellus fermentum ac. Nulla quis velit augue. Fusce accumsan, lacus et lobortis blandit, neque magna gravida enim, dignissim ultricies tortor dui in dolor. Vestibulum vel convallis justo, quis venenatis elit. Aliquam erat volutpat. Nunc quis iaculis ligula. Suspendisse dictum sodales neque vitae faucibus. Fusce id tellus pretium, varius nunc et, placerat metus.</p>\r\n<p>Pellentesque quis facilisis mauris. Phasellus porta, metus a dignissim viverra, est elit luctus erat, nec ultricies ligula lorem eget sapien. Pellentesque ac justo velit. Maecenas semper accumsan nulla eget rhoncus. Aliquam vel urna sed nibh dignissim auctor. Integer volutpat lacus ac purus convallis, at lobortis nisi tincidunt. Vestibulum condimentum elit ac sapien placerat, at ornare libero hendrerit. Cras tincidunt nunc sit amet ante bibendum tempor. Fusce quam orci, suscipit sed eros quis, vulputate molestie metus. Nam hendrerit vitae felis et porttitor. Proin et commodo velit, id porta erat. Donec eu consectetur odio. Fusce porta odio risus. Aliquam vel erat feugiat, vestibulum elit eget, ornare sapien. Sed sed nulla justo. Sed a dolor eu justo lacinia blandit</p>\r\n</div>', '', '', 17, 'a:2:{i:0;s:8:\"side_bar\";i:1;s:6:\"footer\";}', '2014-04-19 17:21:23', '2015-05-16 09:18:39', 1);
";

$insert_permalinks_data = "
  REPLACE INTO `".$this->db->dbprefix."permalinks` (`permalink_id`, `slug`, `controller`, `query`) VALUES
  (11, 'about-us', 'pages', 'page_id=11');
";

$insert_permissions_data = "
  REPLACE INTO `".$this->db->dbprefix."permissions` (`permission_id`, `name`, `description`, `action`, `status`)
  VALUES
    (11, 'Admin.Banners', 'Ability to access, manage, add and delete banners', 'a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}', 1),
    (12, 'Admin.Categories', 'Ability to access, manage, add and delete categories', 'a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}', 1),
    (13, 'Site.Countries', 'Ability to manage, add and delete site countries', 'a:3:{i:0;s:6:\"manage\";i:1;s:3:\"add\";i:2;s:6:\"delete\";}', 1),
    (14, 'Admin.Coupons', 'Ability to access, manage, add and delete coupons', 'a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}', 1),
    (15, 'Site.Currencies', 'Ability to access, manage, add and delete site currencies', 'a:3:{i:0;s:6:\"manage\";i:1;s:3:\"add\";i:2;s:6:\"delete\";}', 1),
    (16, 'Admin.CustomerGroups', 'Ability to access, manage, add and delete customer groups', 'a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}', 1),
    (17, 'Admin.Customers', 'Ability to access, manage, add and delete customers', 'a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}', 1),
    (18, 'Admin.CustomersOnline', 'Ability to access online customers', 'a:1:{i:0;s:6:\"access\";}', 1),
    (19, 'Admin.Maintenance', 'Ability to access, backup, restore and migrate database', 'a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}', 1),
    (20, 'Admin.ErrorLogs', 'Ability to access and delete error logs file', 'a:2:{i:0;s:6:\"access\";i:1;s:6:\"delete\";}', 1),
    (21, 'Admin.Extensions', 'Ability to access, manage, add and delete extension', 'a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}', 1),
    (22, 'Admin.MediaManager', 'Ability to access, manage, add and delete media items', 'a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}', 1),
    (23, 'Site.Languages', 'Ability to manage, add and delete site languages', 'a:3:{i:0;s:6:\"manage\";i:1;s:3:\"add\";i:2;s:6:\"delete\";}', 1),
    (24, 'Site.Layouts', 'Ability to manage, add and delete site layouts', 'a:3:{i:0;s:6:\"manage\";i:1;s:3:\"add\";i:2;s:6:\"delete\";}', 1),
    (25, 'Admin.Locations', 'Ability to access, manage, add and delete locations', 'a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}', 1),
    (26, 'Admin.MailTemplates', 'Ability to access, manage, add and delete mail templates', 'a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}', 1),
    (27, 'Admin.MenuOptions', 'Ability to access, manage, add and delete menu option items', 'a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}', 1),
    (28, 'Admin.Menus', 'Ability to access, manage, add and delete menu items', 'a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}', 1),
    (29, 'Admin.Messages', 'Ability to add and delete messages', 'a:2:{i:0;s:3:\"add\";i:1;s:6:\"delete\";}', 1),
    (30, 'Admin.Orders', 'Ability to access, manage, add and delete orders', 'a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}', 1),
    (31, 'Site.Pages', 'Ability to manage, add and delete site pages', 'a:3:{i:0;s:6:\"manage\";i:1;s:3:\"add\";i:2;s:6:\"delete\";}', 1),
    (32, 'Admin.Payments', 'Ability to access, add and delete extension payments', 'a:3:{i:0;s:6:\"access\";i:1;s:3:\"add\";i:2;s:6:\"delete\";}', 1),
    (33, 'Admin.Permissions', 'Ability to manage, add and delete staffs permissions', 'a:3:{i:0;s:6:\"manage\";i:1;s:3:\"add\";i:2;s:6:\"delete\";}', 1),
    (34, 'Admin.Ratings', 'Ability to add and delete review ratings', 'a:2:{i:0;s:3:\"add\";i:1;s:6:\"delete\";}', 1),
    (35, 'Admin.Reservations', 'Ability to access, manage, add and delete reservations', 'a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}', 1),
    (36, 'Admin.Reviews', 'Ability to access, manage, add and delete user reviews', 'a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}', 1),
    (37, 'Admin.SecurityQuestions', 'Ability to add and delete customer registration security questions', 'a:2:{i:0;s:3:\"add\";i:1;s:6:\"delete\";}', 1),
    (38, 'Site.Settings', 'Ability to manage system settings', 'a:1:{i:0;s:6:\"manage\";}', 1),
    (39, 'Admin.StaffGroups', 'Ability to access, manage, add and delete staff groups', 'a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}', 1),
    (40, 'Admin.Staffs', 'Ability to access, manage, add and delete staffs', 'a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}', 1),
    (42, 'Admin.Statuses', 'Ability to access, manage, add and delete orders and reservations statuses', 'a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}', 1),
    (43, 'Admin.Tables', 'Ability to access, manage, add and delete reservations tables', 'a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}', 1),
    (44, 'Site.Themes', 'Ability to access, manage site themes', 'a:2:{i:0;s:6:\"access\";i:1;s:6:\"manage\";}', 1),
    (45, 'Module.AccountModule', 'Ability to manage account module', 'a:1:{i:0;s:6:\"manage\";}', 1),
    (46, 'Module.BannersModule', 'Ability to manage banners module', 'a:1:{i:0;s:6:\"manage\";}', 1),
    (47, 'Module.CartModule', 'Ability to manage cart module', 'a:1:{i:0;s:6:\"manage\";}', 1),
    (48, 'Module.CategoriesModule', 'Ability to manage categories module', 'a:1:{i:0;s:6:\"manage\";}', 1),
    (49, 'Module.LocalModule', 'Ability to manage local module', 'a:1:{i:0;s:6:\"manage\";}', 1),
    (50, 'Module.PagesModule', 'Ability to manage pages module', 'a:1:{i:0;s:6:\"manage\";}', 1),
    (51, 'Module.ReservationModule', 'Ability to manage reservation module', 'a:1:{i:0;s:6:\"manage\";}', 1),
    (52, 'Module.Slideshow', 'Ability to manage slideshow module', 'a:1:{i:0;s:6:\"manage\";}', 1),
    (53, 'Payment.Cod', 'Ability to manage cash on delivery payment', 'a:1:{i:0;s:6:\"manage\";}', 1),
    (54, 'Payment.PaypalExpress', 'Ability to manage paypal express payment', 'a:1:{i:0;s:6:\"manage\";}', 1);
";

$insert_security_questions_data = "
  REPLACE INTO `".$this->db->dbprefix."security_questions` (`question_id`, `text`, `priority`)
  VALUES
    (11, 'Whats your pets name?', 1),
    (12, 'What high school did you attend?', 2),
    (13, 'What is your father\'s middle name?', 7),
    (14, 'What is your mother\'s name?', 3),
    (15, 'What is your place of birth?', 4),
    (16, 'Whats your favourite teacher\'s name?', 5);
";

$insert_settings_data = "
  REPLACE INTO `".$this->db->dbprefix."settings` (`setting_id`, `sort`, `item`, `value`, `serialized`) VALUES
  (7870, 'prefs', 'mail_template_id', '11', 0),
  (8500, 'ratings', 'ratings', 'a:1:{s:7:\"ratings\";a:5:{i:1;s:3:\"Bad\";i:2;s:5:\"Worse\";i:3;s:4:\"Good\";i:4;s:7:\"Average\";i:5;s:9:\"Excellent\";}}', 1),
  (9225, 'config', 'site_desc', '', 0),
  (9241, 'config', 'search_radius', '20', 0),
  (9249, 'config', 'ready_time', '45', 0),
  (10836, 'prefs', 'default_location_id', '', 0),
  (10839, 'config', 'site_logo', 'data/no_photo.png', 0),
  (10840, 'config', 'country_id', '222', 0),
  (10841, 'config', 'timezone', 'Europe/London', 0),
  (10842, 'config', 'currency_id', '226', 0),
  (10843, 'config', 'language_id', '11', 0),
  (10844, 'config', 'customer_group_id', '11', 0),
  (10845, 'config', 'page_limit', '20', 0),
  (10846, 'config', 'meta_description', '', 0),
  (10847, 'config', 'meta_keywords', '', 0),
  (10848, 'config', 'menus_page_limit', '20', 0),
  (10849, 'config', 'show_menu_images', '1', 0),
  (10850, 'config', 'menu_images_h', '80', 0),
  (10851, 'config', 'menu_images_w', '95', 0),
  (10852, 'config', 'special_category_id', '0', 0),
  (10853, 'config', 'registration_terms', '1', 0),
  (10854, 'config', 'checkout_terms', '0', 0),
  (10855, 'config', 'stock_warning', '0', 0),
  (10856, 'config', 'stock_qty_warning', '0', 0),
  (10857, 'config', 'registration_email', '1', 0),
  (10858, 'config', 'customer_order_email', '1', 0),
  (10859, 'config', 'customer_reserve_email', '1', 0),
  (10860, 'config', 'main_address', 'a:6:{s:9:\"address_1\";s:0:\"\";s:9:\"address_2\";s:0:\"\";s:4:\"city\";s:0:\"\";s:8:\"postcode\";s:0:\"\";s:11:\"location_id\";s:0:\"\";s:10:\"country_id\";s:1:\"1\";}', 1),
  (10861, 'config', 'maps_api_key', '', 0),
  (10863, 'config', 'distance_unit', 'mi', 0),
  (10864, 'config', 'future_orders', '0', 0),
  (10865, 'config', 'location_order', '1', 0),
  (10866, 'config', 'location_order_email', '0', 0),
  (10867, 'config', 'location_reserve_email', '0', 0),
  (10868, 'config', 'approve_reviews', '1', 0),
  (10869, 'config', 'new_order_status', '11', 0),
  (10870, 'config', 'completed_order_status', '15', 0),
  (10878, 'config', 'canceled_order_status', '19', 0),
  (10871, 'config', 'guest_order', '1', 0),
  (10872, 'config', 'delivery_time', '45', 0),
  (10873, 'config', 'collection_time', '15', 0),
  (10874, 'config', 'reservation_mode', '1', 0),
  (10875, 'config',	'new_reservation_status',	'18',	0),
  (10876, 'config',	'confirmed_reservation_status',	'16',	0),
  (10879, 'config',	'canceled_reservation_status',	'17',	0),
  (10880, 'config', 'reservation_time_interval', '45', 0),
  (10881, 'config', 'reservation_stay_time', '60', 0),
  (10882, 'config', 'image_manager', 'a:11:{s:8:\"max_size\";s:3:\"300\";s:11:\"thumb_width\";s:3:\"320\";s:12:\"thumb_height\";s:3:\"220\";s:7:\"uploads\";s:1:\"1\";s:10:\"new_folder\";s:1:\"1\";s:4:\"copy\";s:1:\"1\";s:4:\"move\";s:1:\"1\";s:6:\"rename\";s:1:\"1\";s:6:\"delete\";s:1:\"1\";s:15:\"transliteration\";s:1:\"0\";s:13:\"remember_days\";s:1:\"7\";}', 1),
  (10883, 'config', 'protocol', 'mail', 0),
  (10884, 'config', 'mailtype', 'html', 0),
  (10885, 'config', 'smtp_host', '', 0),
  (10886, 'config', 'smtp_port', '', 0),
  (10887, 'config', 'smtp_user', '', 0),
  (10888, 'config', 'smtp_pass', '', 0),
  (10889, 'config', 'log_threshold', '1', 0),
  (10891, 'config', 'customer_online_time_out', '120', 0),
  (10892, 'config', 'customer_online_archive_time_out', '0', 0),
  (10894, 'config', 'index_file_url', '0', 0),
  (10895, 'config', 'permalink', '1', 0),
  (10896, 'config', 'maintenance_mode', '0', 0),
  (10897, 'config', 'maintenance_message', 'Site is under maintenance. Please check back later.', 0),
  (10898, 'config', 'cache_mode', '0', 0),
  (10899, 'config', 'cache_time', '0', 0);
";

$insert_staff_groups_data = "
  REPLACE INTO `".$this->db->dbprefix."staff_groups` (`staff_group_id`, `staff_group_name`, `location_access`, `permission`) VALUES
    (11, 'Administrator', 0, 'a:44:{i:11;a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}i:12;a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}i:13;a:3:{i:0;s:6:\"manage\";i:1;s:3:\"add\";i:2;s:6:\"delete\";}i:14;a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}i:15;a:3:{i:0;s:6:\"manage\";i:1;s:3:\"add\";i:2;s:6:\"delete\";}i:16;a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}i:17;a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}i:18;a:1:{i:0;s:6:\"access\";}i:19;a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}i:20;a:2:{i:0;s:6:\"access\";i:1;s:6:\"delete\";}i:21;a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}i:22;a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}i:25;a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}i:26;a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}i:27;a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}i:28;a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}i:29;a:2:{i:0;s:3:\"add\";i:1;s:6:\"delete\";}i:30;a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}i:32;a:3:{i:0;s:6:\"access\";i:1;s:3:\"add\";i:2;s:6:\"delete\";}i:33;a:3:{i:0;s:6:\"manage\";i:1;s:3:\"add\";i:2;s:6:\"delete\";}i:34;a:2:{i:0;s:3:\"add\";i:1;s:6:\"delete\";}i:35;a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}i:36;a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}i:37;a:2:{i:0;s:3:\"add\";i:1;s:6:\"delete\";}i:39;a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}i:40;a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}i:41;a:2:{i:0;s:6:\"access\";i:1;s:6:\"manage\";}i:42;a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}i:43;a:4:{i:0;s:6:\"access\";i:1;s:6:\"manage\";i:2;s:3:\"add\";i:3;s:6:\"delete\";}i:23;a:3:{i:0;s:6:\"manage\";i:1;s:3:\"add\";i:2;s:6:\"delete\";}i:24;a:3:{i:0;s:6:\"manage\";i:1;s:3:\"add\";i:2;s:6:\"delete\";}i:31;a:3:{i:0;s:6:\"manage\";i:1;s:3:\"add\";i:2;s:6:\"delete\";}i:38;a:1:{i:0;s:6:\"manage\";}i:44;a:2:{i:0;s:6:\"access\";i:1;s:6:\"manage\";}i:45;a:1:{i:0;s:6:\"manage\";}i:46;a:1:{i:0;s:6:\"manage\";}i:47;a:1:{i:0;s:6:\"manage\";}i:48;a:1:{i:0;s:6:\"manage\";}i:49;a:1:{i:0;s:6:\"manage\";}i:50;a:1:{i:0;s:6:\"manage\";}i:51;a:1:{i:0;s:6:\"manage\";}i:52;a:1:{i:0;s:6:\"manage\";}i:53;a:1:{i:0;s:6:\"manage\";}i:54;a:1:{i:0;s:6:\"manage\";}}');
";

$insert_statuses_data = "
  REPLACE INTO `".$this->db->dbprefix."statuses` (`status_id`, `status_name`, `status_comment`, `notify_customer`, `status_for`, `status_color`)
  VALUES
    (11, 'Received', 'Your order has been received.', 1, 'order', '#686663'),
    (12, 'Pending', 'Your order is pending', 1, 'order', '#f0ad4e'),
    (13, 'Preparation', 'Your order is in the kitchen', 1, 'order', '#00c0ef'),
    (14, 'Delivery', 'Your order will be with you shortly.', 0, 'order', '#00a65a'),
    (15, 'Completed', '', 0, 'order', '#00a65a'),
    (16, 'Confirmed', 'Your table reservation has been confirmed.', 0, 'reserve', '#00a65a'),
    (17, 'Canceled', 'Your table reservation has been canceled.', 0, 'reserve', '#dd4b39'),
    (18, 'Pending', 'Your table reservation is pending.', 0, 'reserve', ''),
    (19, 'Canceled', '', 0, 'order', '#ea0b29');
";

$insert_uri_routes_data = "
  REPLACE INTO `".$this->db->dbprefix."uri_routes` (`uri_route_id`, `uri_route`, `controller`, `priority`)
  VALUES
    (1, 'locations', 'local/locations', 1),
    (2, 'account', 'account/account', 2),
    (3, '(:any)', 'pages', 3);
";