<?php

/**
* DO NOT EDIT THIS FILE, unless you know what you are doing.
*
*/

?>

<style type="text/css">
	body {
	    font-family: <?php echo $font_family; ?>;
	    font-size: <?php echo $font_size; ?>;
	    font-weight: <?php echo $font_weight; ?>;
	    color: <?php echo $font_color; ?>;
	}

	.logo {
    width: <?php echo $logo_width; ?>;
    margin-top: <?php echo $logo_top; ?>;
    margin-left: <?php echo $logo_left; ?>;
	}
</style>