<?php

/**
* DO NOT EDIT THIS FILE, unless you know what you are doing.
*
*/

?>

<style type="text/css">
	body {
	    font-family: <? echo $font_family; ?>;
	    font-size: <?php echo $font_size; ?>;
	    font-weight: <?php echo $font_weight; ?>;
	    color: <?php echo $font_color; ?>;
	}

	.logo img {
        height: <?php echo $logo_height; ?> !important;
    }
	.logo {
        padding-top: <?php echo $logo_padding_top; ?>;
        padding-bottom: <?php echo $logo_padding_bottom; ?>;
	}
    .content-area {
        <?php if (!empty($body['image'])) { ?>
            background-image: url('<?php echo image_url($body['image']); ?>');
            background-repeat: no-repeat;
        <?php } else { ?>
            background-color: <?php echo $body['background']; ?>;
        <?php } ?>
    }
    #heading {
    <?php if (!empty($header['image'])) { ?>
        background-image: url('<?php echo image_url($header['image']); ?>');
        background-repeat: no-repeat;
    <?php } else { ?>
        background-color: <?php echo $header['background']; ?>;
    <?php } ?>
        color: <?php echo $header['color']; ?>;
    }
    .side-bar .panel {
    border-color: <?php echo $sidebar['border']; ?>;
    border-width: 0 1px 1px;
    border-style: solid;
    }
    .side-bar .panel, .side-bar .panel-heading {
    color: <?php echo $sidebar['font']; ?>;
    }
    .side-bar .panel, .side-bar .panel .panel-body {
    background-image: url('<?php echo image_url($sidebar['image']); ?>');
    background-repeat: no-repeat;
    background-color: <?php echo $sidebar['background']; ?>;
    }
    .side-bar .panel .list-group-item {
    background-color: <?php echo $sidebar['background']; ?>;
    border-color: <?php echo $sidebar['border']; ?>;
    color: <?php echo $sidebar['font']; ?>;
    }
    a {
    color: <?php echo $link['color']; ?>;
    }
    a:hover, a:focus{
    color: <?php echo $link['hover']; ?>;
    }
    .btn-default {
    background-color: <?php echo $button['default']['background']; ?>;
    border-color: <?php echo $button['default']['border']; ?>;
    }
    .btn-primary {
    background-color: <?php echo $button['primary']['background']; ?>;
    border-color: <?php echo $button['primary']['border']; ?>;
    }
    .btn-success {
    background-color: <?php echo $button['success']['background']; ?>;
    border-color: <?php echo $button['success']['border']; ?>;
    }
    .btn-danger {
    background-color: <?php echo $button['danger']['background']; ?>;
    border-color: <?php echo $button['danger']['border']; ?>;
    }

    <?php echo $custom_css; ?>
</style>