<?php

/**
 * DO NOT EDIT THIS FILE, unless you know what you are doing.
 *
 */

?>

<?php

$style = "<style type=\"text/css\">";

// Body
$style .= "body {";
if (!empty($font['family']))
	$style .= "font-family: {$font['family']};";

if (!empty($font['size']))
	$style .= "font-size: {$font['size']}px;";

if (!empty($font['weight']))
	$style .= "font-weight: {$font['weight']};";

if (!empty($font['style']))
	$style .= "font-style: {$font['style']};";

if (!empty($font['color']))
	$style .= "color: {$font['color']};";
$style .= "}";

$style .= "body, #page-wrapper {";
if (!empty($body['background']))
	$style .= "background-color: {$body['background']};";

if (!empty($body['image']) AND !empty($body['display'])) {
	$style .= "background-image: url('".image_url($body['image'])."');";

	if ($body['display'] === 'tiled') {
		$style .= "background-repeat: repeat;";
	} else if ($body['display'] === 'centered') {
		$style .= "background-repeat: no-repeat; background-position: center center;";
	} else if ($body['display'] === 'cover') {
		$style .= "background-repeat: no-repeat; background-size:cover;";
	} else {
		$style .= "background-size: {$body['display']};";
	}
}
$style .= "}";

// GENERAL COLOR
if (!empty($body['color'])) {
	$style .= ".local-box-fluid, .local-box-fluid .panel { background-color: {$body['color']}; border-color: {$body['color']}}";
	$style .= ".step-item .icon i { color: {$body['color']}; border-color:{$body['color']};}";
	$style .= ".newsletter-subscribe { background-color: {$body['color']}; color:{$body['foreground']}}";
	$style .= ".nav-tabs-line > li.active > a, .nav-tabs-line > li.active > a:hover, .nav-tabs-line > li.active > a:focus, .nav-tabs-line > li.open a, .nav-tabs-line > li > a:hover, .nav-tabs-line > li > a:focus { border-color: {$sidebar['border']} {$sidebar['border']} {$body['color']};}";
	$style .= ".nav-tabs-line > li.open a, .nav-tabs-line > li:hover, .nav-tabs-line > li:focus, .nav-tabs-line > li.active, .nav-tabs-line > li.active:hover, .nav-tabs-line > li.active:focus { border-color: {$sidebar['border']} {$sidebar['border']} {$body['color']};}";
	$style .= ".nav-tabs-line > li.open a, .nav-tabs-line > li > a:hover, .nav-tabs-line > li > a:focus { background-color: {$sidebar['border']};}";
}

// Header
$style .= "#main-header, #main-header .navbar-collapse, .modal-header {";
if (!empty($header['background']))
	$style .= "background-color: {$header['background']};";

if (!empty($header['image']) AND !empty($header['display'])) {
	$style .= "background-image: url('".image_url($header['image'])."');";

	if ($header['display'] === 'tiled') {
		$style .= "background-repeat: repeat;";
	} else if ($header['display'] === 'centered') {
		$style .= "background-repeat: no-repeat; background-position: center center;";
	} else if ($header['display'] === 'cover') {
		$style .= "background-repeat: no-repeat; background-size:cover;";
	} else {
		$style .= "background-size: {$header['display']};";
	}
}

if (!empty($header['color']))
	$style .= "#main-header .navbar-nav > li > a, .modal-header, .local-box-fluid h2 { color: {$header['color']};}";

if ( ! empty($header['dropdown_background']))
	$style .= "#main-header .dropdown-menu { background-color: {$header['dropdown_background']};}";

// Logo
if (empty($logo_text) AND !empty($logo_height)) {
	$style .= "#main-header .logo img {height: {$logo_height}px !important;}";
} else if ( ! empty($logo_height)) {
	$style .= "#main-header .logo a {font-size: {$logo_height}px !important;}";
}

$style .= "#main-header .logo {";
if ( ! empty($logo_padding_top))
	$style .= "padding-top: {$logo_padding_top}px;}";

if ( ! empty($logo_padding_bottom))
	$style .= "padding-bottom: {$logo_padding_bottom}px;}";
$style .= "}";

// MENU
$style .= "#main-header .navbar-nav > li > a {";
if (!empty($menu_font['family']))
	$style .= "font-family: {$menu_font['family']};";

if (!empty($menu_font['size']))
	$style .= "font-size: {$menu_font['size']}px;";

if (!empty($menu_font['weight']))
	$style .= "font-weight: {$menu_font['weight']};";

if (!empty($menu_font['style']))
	$style .= "font-style: {$menu_font['style']};";

if (!empty($menu_font['color']))
	$style .= "color: {$menu_font['color']};";
$style .= "}";


// FOREGROUND
if ( ! empty($body['foreground'])) {
	$style .= "#page-content div.content { background-color: {$body['foreground']};}";
	$style .= "#page-content div.content-wrap { background-color: {$body['foreground']}; border-width: 1px; border-style: solid; padding:15px; border-radius:4px;margin-bottom: 20px;}";
}

if ( ! empty($body['border']))
	$style .= "#page-content div.content-wrap, #page-content div.content { border-color: {$body['border']};}";

// Heading
$style .= "#heading {";
if (empty($heading['image']) AND !empty($heading['background'])) {
	$style .= "background: {$heading['background']} !important;";
} else if (!empty($heading['image']) AND !empty($heading['display'])) {
	$style .= "background-color: {$heading['background']};";
	$style .= "background-image: url('".image_url($heading['image'])."');";

	if ($heading['display'] === 'tiled') {
		$style .= "background-repeat: repeat;";
	} else if ($heading['display'] === 'centered') {
		$style .= "background-repeat: no-repeat; background-position: center center;";
	} else if ($heading['display'] === 'cover') {
		$style .= "background-repeat: no-repeat; background-size:cover;";
	} else {
		$style .= "background-size: {$heading['display']};";
	}
}

if ( ! empty($heading['color']))
	$style .= "color: {$heading['color']};";
$style .= "}";

$style .= ".under-heading {";
if ( ! empty($heading['under_image'])) {
	$style .= "background-image: url('".image_url($heading['under_image'])."');";
} else if ( isset($heading['under_image']) AND  empty($heading['under_image'])) {
	$style .= "background-image: none; height: auto;";
}
if ( ! empty($heading['under_height']))
	$style .= "height: {$heading['under_height']};";
$style .= "}";

// Sidebar
$style .= "#local-info .panel-local, .side-bar .module-box .panel, .side-bar .module-box:not(#category-box) .panel {";
if (!empty($sidebar['background']))
	$style .= "background-color: {$sidebar['background']};";

if (!empty($sidebar['image'])) {
	$style .= "background-image: url('".image_url($sidebar['image'])."');";

	if ($sidebar['display'] === 'tiled') {
		$style .= "background-repeat: repeat;";
	} else if ($sidebar['display'] === 'centered') {
		$style .= "background-repeat: no-repeat; background-position: center center;";
	} else if ($sidebar['display'] === 'cover') {
		$style .= "background-repeat: no-repeat; background-size:cover;";
	} else {
		$style .= "background-size: {$sidebar['display']};";
	}
}
$style .= "}";

if ( ! empty($sidebar['border']))
	$style .= ".side-bar .panel-default > .panel-heading, .panel-cart .location-control, .panel-cart .cart-coupon, #local-info .panel-local, .panel-local .panel-heading { border-color: {$sidebar['border']};}";

if ( ! empty($sidebar['border']))
	$style .= ".side-bar .panel-cart { border-color: {$sidebar['border']}; border-width: 1px; border-style: solid;}";

$style .= ".side-bar .module-box li, .side-bar > .module-box .list-group-item, #category-box .list-group-item a, .cart-items ul li {";
if ( ! empty($sidebar['border']))
	$style .= "background-color: transparent;border-color: {$sidebar['border']}; border-width: 0 0 1px; border-style: solid;";
$style .= "}";

if ( ! empty($sidebar['font']))
	$style .= ".side-bar .module-box .panel, .side-bar .list-group-item a { color: {$sidebar['font']};}";

// Link
if ( ! empty($link['color'])) {
	$style .= "a, .btn-link { color: {$link['color']};}";
}

if ( ! empty($link['hover'])) {
	$style .= "a:hover, a:focus,";
	$style .= "#page-footer .main-footer a:hover, #page-footer .main-footer a:focus,";
	$style .= "#page-footer .bottom-footer a:hover, #page-footer .bottom-footer a:focus,";
	$style .= ".side-bar a.list-group-item:hover, .side-bar .list-group-item > a:hover,";
	$style .= ".side-bar a.list-group-item.active, .side-bar .list-group-item > a.active { color: {$link['color']};text-decoration: none;}";
}

// Button
if ( ! empty($button['default']['background'])) {
	$style .= ".btn-default { background-color: {$button['default']['background']}; border-color: {$button['default']['background']};}";
	$style .= ".panel-default .panel-heading, .panel-nav-tabs.panel-default .panel-heading { background-color: {$button['default']['background']}}";
}

if ( ! empty($button['default']['hover'])) {
	$style .= ".btn-default:hover, .btn-default:focus, .btn-default.active, .btn-default:active { background-color: {$button['default']['hover']}; border-color: {$button['default']['hover']};}";
	$style .= ".panel-default, .panel-default .panel-heading, .panel-nav-tabs.panel-default .panel-heading { border-color: {$button['default']['hover']}}";
}

if ( ! empty($button['primary']['background'])) {
	$style .= ".btn-primary { background-color: {$button['primary']['background']}; border-color: {$button['primary']['background']};}";
	$style .= ".panel-primary, .panel-primary .panel-heading, .panel-nav-tabs.panel-primary .panel-heading { border-color: {$button['primary']['background']}}";
}

if ( ! empty($button['primary']['hover']))
	$style .= ".btn-primary:hover, .btn-primary:focus, .btn-primary.active, .btn-primary:active { background-color: {$button['primary']['hover']}; border-color: {$button['primary']['hover']};}";

if ( ! empty($button['success']['background'])) {
	$style .= ".btn-success { background-color: {$button['success']['background']}; border-color: {$button['success']['background']};}";
	$style .= ".panel-success, .panel-success .panel-heading, .panel-nav-tabs.panel-success .panel-heading { border-color: {$button['success']['background']}}";
}

if ( ! empty($button['success']['hover']))
	$style .= ".btn-success:hover, .btn-success:focus, .btn-success.active, .btn-success:active { background-color: {$button['success']['hover']}; border-color: {$button['success']['hover']};}";

if ( ! empty($button['danger']['background'])) {
	$style .= ".btn-danger { background-color: {$button['danger']['background']}; border-color: {$button['danger']['background']};}";
	$style .= ".panel-danger, .panel-danger .panel-heading, .panel-nav-tabs.panel-danger .panel-heading { border-color: {$button['danger']['background']}}";
}

if ( ! empty($button['danger']['hover']))
	$style .= ".btn-danger:hover, .btn-danger:focus, .btn-danger.active, .btn-danger:active { background-color: {$button['danger']['hover']}; border-color: {$button['danger']['hover']};}";

// Footer
$style .= "#page-footer {";
if (!empty($footer['background']))
	$style .= "background-color: {$footer['background']}; background-image:linear-gradient(to bottom, {$footer['background']}, {$footer['background']});";

if (!empty($footer['image']) AND !empty($header['display'])) {
	$style .= "background-image: url('".image_url($footer['image'])."');";

	if ($footer['display'] === 'tiled') {
		$style .= "background-repeat: repeat;";
	} else if ($footer['display'] === 'centered') {
		$style .= "background-repeat: no-repeat; background-position: center center;";
	} else if ($footer['display'] === 'cover') {
		$style .= "background-repeat: no-repeat; background-size:cover;";
	} else {
		$style .= "background-size: {$footer['display']};";
	}
}
$style .= "}";

$style .= "#page-footer .bottom-footer {";
if ( ! empty($footer['bottom_background']))
	$style .= "background-color: {$footer['bottom_background']};";

if ( ! empty($footer['bottom_image']) AND ! empty($footer['bottom_display'])) {
	$style .= "background-image: url('" . image_url($footer['bottom_image']) . "'); background-position: center center;background-repeat: no-repeat;";

	if ($footer['bottom_display'] === 'tiled') {
		$style .= "background-repeat: repeat;";
	} else if ($footer['bottom_display'] === 'centered') {
		$style .= "background-repeat: no-repeat; background-position: center center;";
	} else if ($footer['bottom_display'] === 'cover') {
		$style .= "background-repeat: no-repeat; background-size:cover;";
	} else {
		$style .= "background-size: {$footer['bottom_display']};";
	}
}
$style .= "}";

if ( ! empty($footer['footer_color'])) {
	$style .= "#page-footer .main-footer, #page-footer .main-footer a { color: {$footer['footer_color']};}";
}
if ( ! empty($footer['bottom_footer_color'])) {
	$style .= "#page-footer .bottom-footer, #page-footer .bottom-footer a { color: {$footer['bottom_footer_color']};}";
}

if ( ! empty($custom_script['css'])) {
	echo $style . $custom_script['css'];
} else {
	echo $style;
}
?>
</style>