<?php defined('BASEPATH') OR exit('No direct script access allowed');

/*
 * DO NOT EDIT THIS FILE.... AS IT WILL BREAK THE SYSTEM.
 */

/*
| -------------------------------------------------------------------
| AUTO-LOADER
| -------------------------------------------------------------------
| This file specifies which systems should be loaded by default.
|
| DO NOT EDIT THIS FILE.... AS IT WILL BREAK THE SYSTEM.
|
| To autoload resources create a separate autoload.php file
| within your extension or use the $autoload property of your
| Extension class.
|
| In order to keep TastyIgniter as light-weight as possible only the
| absolute minimal resources are loaded by default. For example,
| the database is not connected to automatically since no assumption
| is made regarding whether you intend to use it.
|
| -------------------------------------------------------------------
| Instructions
| -------------------------------------------------------------------
|
| These are the things you can load automatically:
|
| 1. Packages
| 2. Libraries
| 3. Drivers
| 4. Helper files
| 5. Custom config files
| 6. Language files
| 7. Models
|
*/

/*
| -------------------------------------------------------------------
|  Auto-load Packages
| -------------------------------------------------------------------
| These are the classes located in system/ use your
| your Extension Class $autoload property instead or
| create a autoload.php file within your extension folder
|
| Prototype:
|
|  $autoload['packages'] = array(APPPATH.'third_party', '/usr/local/shared');
|
*/
$autoload['packages'] = [];

/*
| -------------------------------------------------------------------
|  Auto-load Libraries
| -------------------------------------------------------------------
| These are the classes located in system/ use your
| your Extension Class $autoload property instead
|
| Prototype:
|
|	$autoload['libraries'] = array('database', 'email', 'session');
|
| You can also supply an alternative library name to be assigned
| in the controller:
|
|	$autoload['libraries'] = array('user_agent' => 'ua');
*/

$autoload['libraries'] = [
    'user_agent',
    'session',
    'alert',
    'installer',
    'events',
    'theme_manager',
    'template',
];

/*
| -------------------------------------------------------------------
|  Auto-load Drivers
| -------------------------------------------------------------------
| These are the drivers located in system/ use your
| your Extension Class $autoload property instead or
| create a autoload.php file within your extension folder
|
| Prototype:
|
|	$autoload['drivers'] = array('cache');
|
| You can also supply an alternative property name to be assigned in
| the controller:
|
|	$autoload['drivers'] = array('cache' => 'cch');
|
*/
$autoload['drivers'] = [];

/*
| -------------------------------------------------------------------
|  Auto-load Helper Files
| -------------------------------------------------------------------
| These are the helpers located in system/ use your
| your Extension Class $autoload property instead or
| create a autoload.php file within your extension folder
|
| Prototype:
|
|	$autoload['helper'] = array('url', 'file');
*/
$autoload['helper'] = [
    'tastyigniter',
    'language',
    'path',
    'url',
    'html',
    'form',
    'inflector',
    'text',
    'array',
    'number',
    'date',
];

/*
| -------------------------------------------------------------------
|  Auto-load Config files
| -------------------------------------------------------------------
| These are the config located in system/ use your
| your Extension Class $autoload property instead or
| create a autoload.php file within your extension folder
|
| Prototype:
|
|	$autoload['config'] = array('config1', 'config2');
|
*/
$autoload['config'] = [];

/*
| -------------------------------------------------------------------
|  Auto-load Language files
| -------------------------------------------------------------------
| These are the language located in system/ use your
| your Extension Class $autoload property instead or
| create a autoload.php file within your extension folder
|
| Prototype:
|
|	$autoload['language'] = array('lang1', 'lang2');
|
| NOTE: Do not include the "_lang" part of your file.  For example
| "codeigniter_lang.php" would be referenced as array('codeigniter');
|
*/
$autoload['language'] = [
    'tastyigniter',
    'default',
];

/*
| -------------------------------------------------------------------
|  Auto-load Models
| -------------------------------------------------------------------
| These are the classes located in system/ use your
| your extensions' Extension Class $autoload property instead or
| create a autoload.php file within your extension folder
|
| Prototype:
|
|	$autoload['model'] = array('first_model', 'second_model');
|
| You can also supply an alternative model name to be assigned
| in the controller:
|
|	$autoload['model'] = array('first_model' => 'first');
*/
$autoload['model'] = [];
