@extends('igniter::admin.layouts.admin')
@section('content')
<div class="container-fluid py-3 pos-foundation">
  <div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-3"><div><h1>{{ lang('Naxas.RestaurantOps::default.pos.title') }}</h1><div class="text-muted">{{ app(\Naxas\RestaurantOps\Contracts\LocationContextContract::class)->current()?->location_name }}</div></div><div class="alert {{ $shift ? 'alert-success' : 'alert-danger' }} m-0">{{ $shift ? 'Shift #'.$shift->getKey().' — open' : lang('Naxas.RestaurantOps::default.pos.no_shift') }}</div></div>
  <div class="row g-3">
    <section class="col-lg-7"><div class="card h-100"><div class="card-body"><div class="btn-group w-100 mb-3" role="group"><button class="btn btn-lg btn-primary">Dine-in</button><button class="btn btn-lg btn-outline-primary">Delivery</button><button class="btn btn-lg btn-outline-primary">Collection</button></div><input class="form-control form-control-lg mb-3" placeholder="{{ lang('Naxas.RestaurantOps::default.pos.search') }}"><div class="row g-2"><div class="col-6 col-md-4"><button class="btn btn-light border w-100 py-4" disabled>{{ lang('Naxas.RestaurantOps::default.pos.catalog') }}<br><small>Server search/configuration endpoint</small></button></div></div></div></div></section>
    <section class="col-lg-5"><div class="card"><div class="card-header"><strong>{{ lang('Naxas.RestaurantOps::default.pos.order') }}</strong></div><div class="card-body"><label class="form-label">{{ lang('Naxas.RestaurantOps::default.pos.customer') }}</label><input class="form-control mb-3" {{ $shift ? '' : 'disabled' }}><textarea class="form-control mb-3" placeholder="Order note" {{ $shift ? '' : 'disabled' }}></textarea><div class="p-3 bg-light rounded mb-3"><strong>{{ lang('Naxas.RestaurantOps::default.pos.totals') }}</strong><div class="d-flex justify-content-between"><span>Total</span><span>0.0000</span></div></div><div class="d-grid gap-2"><button class="btn btn-lg btn-outline-secondary" {{ $shift ? '' : 'disabled' }}>{{ lang('Naxas.RestaurantOps::default.pos.hold') }}</button><button class="btn btn-lg btn-success" {{ $shift ? '' : 'disabled' }}>{{ lang('Naxas.RestaurantOps::default.pos.confirm') }}</button><button class="btn btn-lg btn-warning" disabled>{{ lang('Naxas.RestaurantOps::default.pos.kitchen') }}</button><button class="btn btn-lg btn-primary" disabled>{{ lang('Naxas.RestaurantOps::default.pos.payment') }}</button></div></div></div></section>
  </div>
  <section class="mt-3"><h2 class="h4">{{ lang('Naxas.RestaurantOps::default.navigation.held_orders') }}</h2><div class="list-group">@forelse($held as $order)<a class="list-group-item list-group-item-action" href="{{ admin_url('restaurant-ops/pos/orders/'.$order->getKey()) }}">#{{ $order->getKey() }} — {{ $order->service_type }} — {{ $order->order_total }}</a>@empty<div class="text-muted">No held orders for this shift.</div>@endforelse</div></section>
</div>
@endsection
