<?php

return [
    'system::lang.mail_variables.text_group_global' => [
        '{{ $site_name }}' => 'system::lang.mail_variables.text_site_name',
        '{{ $site_logo }}' => 'system::lang.mail_variables.text_site_logo',
    ],
    'system::lang.mail_variables.text_group_staff_reset' => [
        '{{ $staff_name }}' => 'system::lang.mail_variables.text_staff_name',
        '{{ $reset_link }}' => 'system::lang.mail_variables.text_staff_reset_link',
    ],
    'system::lang.mail_variables.text_group_registration' => [
        '{{ $first_name }}' => 'system::lang.mail_variables.text_first_name',
        '{{ $last_name }}' => 'system::lang.mail_variables.text_last_name',
        '{{ $account_login_link }}' => 'system::lang.mail_variables.text_account_login_link',
    ],
    'system::lang.mail_variables.text_group_reset' => [
        '{{ $first_name }}' => 'system::lang.mail_variables.text_first_name',
        '{{ $last_name }}' => 'system::lang.mail_variables.text_last_name',
        '{{ $reset_code }}' => 'system::lang.mail_variables.text_reset_code',
        '{{ $reset_link }}' => 'system::lang.mail_variables.text_reset_link',
        '{{ $account_login_link }}' => 'system::lang.mail_variables.text_account_login_link',
    ],
    'system::lang.mail_variables.text_group_order' => [
        '{{ $order_number }}' => 'system::lang.mail_variables.text_order_number',
        '{{ $first_name }}' => 'system::lang.mail_variables.text_first_name',
        '{{ $last_name }}' => 'system::lang.mail_variables.text_last_name',
        '{{ $email }}' => 'system::lang.mail_variables.text_email',
        '{{ $telephone }}' => 'system::lang.mail_variables.text_telephone',
        '{{ $customer_name }}' => 'system::lang.mail_variables.text_customer_name',
        '{{ $order_type }}' => 'system::lang.mail_variables.text_order_type',
        '{{ $order_time }}' => 'system::lang.mail_variables.text_order_time',
        '{{ $order_date }}' => 'system::lang.mail_variables.text_order_date',
        '{{ $order_payment }}' => 'system::lang.mail_variables.text_order_payment',
        '{{ $order_address }}' => 'system::lang.mail_variables.text_order_address',
        '{{ $invoice_number }}' => 'system::lang.mail_variables.text_invoice_number',
        '{{ $invoice_date }}' => 'system::lang.mail_variables.text_invoice_date',
        '{{ $order_comment }}' => 'system::lang.mail_variables.text_order_comment',
        '{{ $location_name }}' => 'system::lang.mail_variables.text_location_name',
        '{{ $location_email }}' => 'system::lang.mail_variables.text_location_email',
        '{{ $location_address }}' => 'system::lang.mail_variables.text_location_address',
        '{{ $status_name }}' => 'system::lang.mail_variables.text_status_name',
        '{{ $status_comment }}' => 'system::lang.mail_variables.text_status_comment',
        '{{ $order_view_url }}' => 'system::lang.mail_variables.text_order_view_url',
        '$order_menus[]' => 'system::lang.mail_variables.text_order_menus',
        '{{ $order_menu[\'menu_name\'] }}' => 'system::lang.mail_variables.text_menu_name',
        '{{ $order_menu[\'menu_quantity\'] }}' => 'system::lang.mail_variables.text_menu_quantity',
        '{{ $order_menu[\'menu_price\'] }}' => 'system::lang.mail_variables.text_menu_price',
        '{{ $order_menu[\'menu_subtotal\'] }}' => 'system::lang.mail_variables.text_menu_subtotal',
        '{!! $order_menu[\'menu_options\'] !!}' => 'system::lang.mail_variables.text_menu_options',
        '{{ $order_menu[\'menu_comment\'] }}' => 'system::lang.mail_variables.text_menu_comment',
        '$order_totals[]' => 'system::lang.mail_variables.text_order_totals',
        '{{ $order_total[\'order_total_title\'] }}' => 'system::lang.mail_variables.text_order_total_title',
        '{{ $order_total[\'order_total_value\'] }}' => 'system::lang.mail_variables.text_order_total_value',
        '{{ $order_total[\'priority\'] }}' => 'system::lang.mail_variables.text_priority',
    ],
    'system::lang.mail_variables.text_group_reservation' => [
        '{{ $reservation_number }}' => 'system::lang.mail_variables.text_reservation_number',
        '{{ $reservation_date }}' => 'system::lang.mail_variables.text_reservation_date',
        '{{ $reservation_time }}' => 'system::lang.mail_variables.text_reservation_time',
        '{{ $reservation_guest_no }}' => 'system::lang.mail_variables.text_reservation_guest_no',
        '{{ $first_name }}' => 'system::lang.mail_variables.text_first_name',
        '{{ $last_name }}' => 'system::lang.mail_variables.text_last_name',
        '{{ $email }}' => 'system::lang.mail_variables.text_email',
        '{{ $telephone }}' => 'system::lang.mail_variables.text_telephone',
        '{{ $reservation_comment }}' => 'system::lang.mail_variables.text_reservation_comment',
        '{{ $location_name }}' => 'system::lang.mail_variables.text_location_name',
        '{{ $location_email }}' => 'system::lang.mail_variables.text_location_email',
        '{{ $location_address }}' => 'system::lang.mail_variables.text_location_address',
        '{{ $status_name }}' => 'system::lang.mail_variables.text_status_name',
        '{{ $status_comment }}' => 'system::lang.mail_variables.text_status_comment',
        '{{ $reservation_view_url }}' => 'system::lang.mail_variables.text_reservation_view_url',
    ],
    'system::lang.mail_variables.text_group_contact' => [
        '{{ $full_name }}' => 'system::lang.mail_variables.text_full_name',
        '{{ $contact_email }}' => 'system::lang.mail_variables.text_contact_email',
        '{{ $contact_telephone }}' => 'system::lang.mail_variables.text_contact_telephone',
        '{{ $contact_topic }}' => 'system::lang.mail_variables.text_contact_topic',
        '{{ $contact_message }}' => 'system::lang.mail_variables.text_contact_message',
    ],
];