<?php
$config['form']['toolbar'] = [
    'buttons' => [
        'save'      => ['label' => 'lang:admin::default.button_save', 'class' => 'btn btn-primary', 'data-request-form' => '#edit-form', 'data-request' => 'onSave'],
        'saveClose' => [
            'label'             => 'lang:admin::default.button_save_close',
            'class'             => 'btn btn-default',
            'data-request'      => 'onSave',
            'data-request-form' => '#edit-form',
            'data-request-data' => 'close:1',
        ],
    ],
];

$config['form']['general'] = [
    'label'       => 'lang:system::settings.text_tab_general',
    'description' => 'lang:system::settings.text_tab_desc_general',
    'icon'        => 'fa fa-sliders',
    'priority'    => 0,
    'url'         => admin_url('settings/edit/general'),
    'form'        => [
        'tabs'  => [
            'fields' => [
                'site_name'          => [
                    'label' => 'lang:system::settings.label_site_name',
                    'tab'   => 'lang:system::settings.text_tab_restaurant',
                    'type'  => 'text',
                    'span'  => 'left',
                ],
                'site_email'         => [
                    'label' => 'lang:system::settings.label_site_email',
                    'tab'   => 'lang:system::settings.text_tab_restaurant',
                    'type'  => 'text',
                    'span'  => 'right',
                ],
                'site_url'           => [
                    'label'   => 'lang:system::settings.label_site_url',
                    'tab'     => 'lang:system::settings.text_tab_restaurant',
                    'type'    => 'text',
                    'span'    => 'left',
                    'default' => root_url(),
                ],
                'country_id'         => [
                    'label'   => 'lang:system::settings.label_country',
                    'tab'     => 'lang:system::settings.text_tab_restaurant',
                    'type'    => 'select',
                    'span'    => 'right',
                    'options' => ['System\Models\Countries_model', 'getDropdownOptions'],
                ],
                'site_location_mode' => [
                    'label'        => 'lang:system::settings.label_site_location_mode',
                    'tab'          => 'lang:system::settings.text_tab_restaurant',
                    'type'         => 'radio',
                    'span'         => 'left',
                    'options'      => [
                        'single'   => 'lang:system::settings.text_single',
                        'multiple' => 'lang:system::settings.text_multiple',
                    ],
                    'comment'      => 'lang:system::settings.help_site_location_mode',
                    'commentAbove' => '<span class="text-danger">System</span>',
                ],
                'site_logo'          => [
                    'label' => 'lang:system::settings.label_site_logo',
                    'tab'   => 'lang:system::settings.text_tab_restaurant',
                    'type'  => 'mediafinder',
                ],
                'maps'               => [
                    'label' => 'lang:system::settings.text_tab_title_maps',
                    'tab'   => 'lang:system::settings.text_tab_restaurant',
                    'type'  => 'section',
                ],
                'maps_api_key'       => [
                    'label'   => 'lang:system::settings.label_maps_api_key',
                    'tab'     => 'lang:system::settings.text_tab_restaurant',
                    'type'    => 'text',
                    'comment' => 'lang:system::settings.help_maps_api_key',
                ],
                'distance_unit'      => [
                    'label'   => 'lang:system::settings.label_distance_unit',
                    'tab'     => 'lang:system::settings.text_tab_restaurant',
                    'type'    => 'radio',
                    'options' => [
                        'mi' => 'lang:system::settings.text_miles',
                        'km' => 'lang:system::settings.text_kilometers',
                    ],
                ],

                'page_limit'            => [
                    'label'   => 'lang:system::settings.label_page_limit',
                    'tab'     => 'lang:system::settings.text_tab_site',
                    'span'    => 'left',
                    'type'    => 'radio',
                    'options' => 'getPageLimitOptions',
                    'comment' => 'lang:system::settings.help_page_limit',
                ],
                'language'              => [
                    'label' => 'lang:system::settings.text_tab_title_language',
                    'tab'   => 'lang:system::settings.text_tab_site',
                    'type'  => 'section',
                ],
                'default_language'      => [
                    'label'       => 'lang:system::settings.label_site_language',
                    'tab'         => 'lang:system::settings.text_tab_site',
                    'type'        => 'select',
                    'default'     => 'en',
                    'span'        => 'left',
                    'options'     => ['System\Models\Languages_model', 'getDropdownOptions'],
                    'placeholder' => 'lang:admin::default.text_please_select',
                ],
                'supported_languages'   => [
                    'label'       => 'lang:system::settings.label_supported_languages',
                    'tab'         => 'lang:system::settings.text_tab_site',
                    'type'        => 'select',
                    'multiOption' => TRUE,
                    'default'     => ['en'],
                    'span'        => 'right',
                    'options'     => ['System\Models\Languages_model', 'getDropdownOptions'],
                    'placeholder' => 'lang:admin::default.text_please_select',
                ],
                'detect_language'       => [
                    'label'   => 'lang:system::settings.label_detect_language',
                    'tab'     => 'lang:system::settings.text_tab_site',
                    'span'    => 'left',
                    'type'    => 'switch',
                    'comment' => 'lang:system::settings.help_detect_language',
                ],
                'currency'              => [
                    'label' => 'lang:system::settings.text_tab_title_currency',
                    'tab'   => 'lang:system::settings.text_tab_site',
                    'type'  => 'section',
                ],
                'default_currency_code' => [
                    'label'       => 'lang:system::settings.label_site_currency',
                    'tab'         => 'lang:system::settings.text_tab_site',
                    'span'        => 'left',
                    'type'        => 'select',
                    'options'     => ['System\Models\Currencies_model', 'getDropdownOptions'],
                    'placeholder' => 'lang:admin::default.text_please_select',
                ],
                'accepted_currencies'   => [
                    'label'       => 'lang:system::settings.label_accepted_currency',
                    'tab'         => 'lang:system::settings.text_tab_site',
                    'type'        => 'select',
                    'span'        => 'right',
                    'multiOption' => TRUE,
                    'options'     => ['System\Models\Currencies_model', 'getDropdownOptions'],
                    'comment'     => 'lang:system::settings.help_accepted_currency',
                    'placeholder' => 'lang:admin::default.text_please_select',
                ],
                'date'                  => [
                    'label' => 'lang:system::settings.text_tab_title_date_time',
                    'tab'   => 'lang:system::settings.text_tab_site',
                    'type'  => 'section',
                ],
                'timezone'              => [
                    'label'       => 'lang:system::settings.label_timezone',
                    'tab'         => 'lang:system::settings.text_tab_site',
                    'type'        => 'select',
                    'options'     => 'listTimezones',
                    'comment'     => 'lang:system::settings.help_timezone',
                    'placeholder' => 'lang:admin::default.text_please_select',
                ],
                'date_format'           => [
                    'label'   => 'lang:system::settings.label_date_format',
                    'tab'     => 'lang:system::settings.text_tab_site',
                    'span'    => 'left',
                    'type'    => 'select',
                    'default' => 'd/m/Y',
                ],
                'time_format'           => [
                    'label'   => 'lang:system::settings.label_time_format',
                    'tab'     => 'lang:system::settings.text_tab_site',
                    'span'    => 'right',
                    'type'    => 'select',
                    'default' => 'h:i a',
                ],
            ],
        ],
        'rules' => [
            ['site_name', 'lang:system::settings.label_site_name', 'required|min:2|max:128'],
            ['site_email', 'lang:system::settings.label_site_email', 'required|email'],
            ['site_logo', 'lang:system::settings.label_site_logo', 'required'],
            ['timezone', 'lang:system::settings.label_timezone', 'required'],
            ['date_format', 'lang:system::settings.label_date_format', 'required'],
            ['time_format', 'lang:system::settings.label_time_format', 'required'],
            ['default_currency_code', 'lang:system::settings.label_site_currency', 'required|string'],
            ['site_location_mode', 'lang:system::settings.label_site_location_mode', 'required|string'],
            ['accepted_currencies.*', 'lang:system::settings.label_accepted_currency', 'required|string'],
            ['detect_language', 'lang:system::settings.label_detect_language', 'required|integer'],
            ['default_language', 'lang:system::settings.label_site_language', 'required'],
            ['supported_languages.*', 'lang:system::settings.label_supported_languages', 'required'],
            ['page_limit', 'lang:system::settings.label_page_limit', 'required|integer'],
            ['country_id', 'lang:system::settings.label_country', 'required|integer'],
            ['maps_api_key', 'lang:system::settings.label_maps_api_key'],
            ['distance_unit', 'lang:system::settings.label_distance_unit'],
        ],
    ],
];

$config['form']['setup'] = [
    'label'       => 'lang:system::settings.text_tab_setup',
    'description' => 'lang:system::settings.text_tab_desc_setup',
    'icon'        => 'fa fa-toggle-on',
    'priority'    => 1,
    'url'         => admin_url('settings/edit/setup'),
    'form'        => [
        'tabs'  => [
            'fields' => [
                'guest_order'             => [
                    'label'   => 'lang:system::settings.label_guest_order',
                    'tab'     => 'lang:system::settings.text_tab_title_order',
                    'type'    => 'switch',
                    'on'      => 'lang:admin::default.text_yes',
                    'off'     => 'lang:admin::default.text_no',
                    'comment' => 'lang:system::settings.help_guest_order',
                ],
                'location_order'          => [
                    'label'   => 'lang:system::settings.label_location_order',
                    'tab'     => 'lang:system::settings.text_tab_title_order',
                    'type'    => 'switch',
                    'on'      => 'lang:admin::default.text_yes',
                    'off'     => 'lang:admin::default.text_no',
                    'comment' => 'lang:system::settings.help_location_order',
                ],
                'order_email'             => [
                    'label'   => 'lang:system::settings.label_order_email',
                    'tab'     => 'lang:system::settings.text_tab_title_order',
                    'type'    => 'checkbox',
                    'options' => [
                        'customer' => 'lang:system::settings.text_to_customer',
                        'admin'    => 'lang:system::settings.text_to_admin',
                        'location' => 'lang:system::settings.text_to_location',
                    ],
                    'comment' => 'lang:system::settings.help_order_email',
                ],
                'default_order_status'    => [
                    'label'       => 'lang:system::settings.label_default_order_status',
                    'tab'         => 'lang:system::settings.text_tab_title_order',
                    'type'        => 'select',
                    'options'     => ['Admin\Models\Statuses_model', 'getDropdownOptionsForOrder'],
                    'comment'     => 'lang:system::settings.help_default_order_status',
                    'placeholder' => 'lang:admin::default.text_please_select',
                ],
                'processing_order_status' => [
                    'label'       => 'lang:system::settings.label_processing_order_status',
                    'tab'         => 'lang:system::settings.text_tab_title_order',
                    'type'        => 'select',
                    'multiOption' => TRUE,
                    'options'     => ['Admin\Models\Statuses_model', 'getDropdownOptionsForOrder'],
                    'comment'     => 'lang:system::settings.help_processing_order_status',
                ],
                'completed_order_status'  => [
                    'label'       => 'lang:system::settings.label_completed_order_status',
                    'tab'         => 'lang:system::settings.text_tab_title_order',
                    'type'        => 'select',
                    'multiOption' => TRUE,
                    'options'     => ['Admin\Models\Statuses_model', 'getDropdownOptionsForOrder'],
                    'comment'     => 'lang:system::settings.help_completed_order_status',
                ],
                'canceled_order_status'   => [
                    'label'       => 'lang:system::settings.label_canceled_order_status',
                    'tab'         => 'lang:system::settings.text_tab_title_order',
                    'type'        => 'select',
                    'options'     => ['Admin\Models\Statuses_model', 'getDropdownOptionsForOrder'],
                    'comment'     => 'lang:system::settings.help_canceled_order_status',
                    'placeholder' => 'lang:admin::default.text_please_select',
                ],

                'reservation_email'            => [
                    'label'   => 'lang:system::settings.label_reservation_email',
                    'tab'     => 'lang:system::settings.text_tab_title_reservation',
                    'type'    => 'checkbox',
                    'options' => [
                        'customer' => 'lang:system::settings.text_to_customer',
                        'admin'    => 'lang:system::settings.text_to_admin',
                        'location' => 'lang:system::settings.text_to_location',
                    ],
                    'comment' => 'lang:system::settings.help_reservation_email',
                ],
                'default_reservation_status'   => [
                    'label'       => 'lang:system::settings.label_default_reservation_status',
                    'tab'         => 'lang:system::settings.text_tab_title_reservation',
                    'type'        => 'select',
                    'options'     => ['Admin\Models\Statuses_model', 'getDropdownOptionsForReservation'],
                    'comment'     => 'lang:system::settings.help_default_reservation_status',
                    'placeholder' => 'lang:admin::default.text_please_select',
                ],
                'confirmed_reservation_status' => [
                    'label'       => 'lang:system::settings.label_confirmed_reservation_status',
                    'tab'         => 'lang:system::settings.text_tab_title_reservation',
                    'type'        => 'select',
                    'options'     => ['Admin\Models\Statuses_model', 'getDropdownOptionsForReservation'],
                    'comment'     => 'lang:system::settings.help_confirmed_reservation_status',
                    'placeholder' => 'lang:admin::default.text_please_select',
                ],
                'canceled_reservation_status'  => [
                    'label'       => 'lang:system::settings.label_canceled_reservation_status',
                    'tab'         => 'lang:system::settings.text_tab_title_reservation',
                    'type'        => 'select',
                    'options'     => ['Admin\Models\Statuses_model', 'getDropdownOptionsForReservation'],
                    'comment'     => 'lang:system::settings.help_canceled_reservation_status',
                    'placeholder' => 'lang:admin::default.text_please_select',
                ],

                'invoice_prefix' => [
                    'label'   => 'lang:system::settings.label_invoice_prefix',
                    'tab'     => 'lang:system::settings.text_tab_title_invoice',
                    'type'    => 'text',
                    'comment' => 'lang:system::settings.help_invoice_prefix',
                ],
                'auto_invoicing' => [
                    'label'   => 'lang:system::settings.label_auto_invoicing',
                    'tab'     => 'lang:system::settings.text_tab_title_invoice',
                    'type'    => 'switch',
                    'on'      => 'lang:system::settings.text_auto',
                    'off'     => 'lang:system::settings.text_manual',
                    'comment' => 'lang:system::settings.help_auto_invoicing',
                ],

                'allow_reviews'   => [
                    'label'   => 'lang:system::settings.label_allow_reviews',
                    'tab'     => 'lang:system::settings.text_tab_title_reviews',
                    'type'    => 'switch',
                    'on'      => 'lang:admin::default.text_yes',
                    'off'     => 'lang:admin::default.text_no',
                    'comment' => 'lang:system::settings.help_allow_reviews',
                ],
                'approve_reviews' => [
                    'label'   => 'lang:system::settings.label_approve_reviews',
                    'tab'     => 'lang:system::settings.text_tab_title_reviews',
                    'type'    => 'switch',
                    'on'      => 'lang:system::settings.text_auto',
                    'off'     => 'lang:system::settings.text_manual',
                    'comment' => 'lang:system::settings.help_approve_reviews',
                    'trigger' => [
                        'action'    => 'show',
                        'field'     => 'allow_reviews',
                        'condition' => 'checked',
                    ],
                ],

                'tax_mode'            => [
                    'label'   => 'lang:system::settings.label_tax_mode',
                    'tab'     => 'lang:system::settings.text_tab_title_taxation',
                    'type'    => 'switch',
                    'comment' => 'lang:system::settings.help_tax_mode',
                ],
                'tax_percentage'      => [
                    'label'   => 'lang:system::settings.label_tax_percentage',
                    'tab'     => 'lang:system::settings.text_tab_title_taxation',
                    'type'    => 'number',
                    'default' => 0,
                    'comment' => 'lang:system::settings.help_tax_percentage',
                ],
                'tax_menu_price'      => [
                    'label'   => 'lang:system::settings.label_tax_menu_price',
                    'tab'     => 'lang:system::settings.text_tab_title_taxation',
                    'type'    => 'select',
                    'options' => [
                        'lang:system::settings.text_menu_price_include_tax',
                        'lang:system::settings.text_apply_tax_on_menu_price',
                    ],
                    'comment' => 'lang:system::settings.help_tax_menu_price',
                ],
                'tax_delivery_charge' => [
                    'label'   => 'lang:system::settings.label_tax_delivery_charge',
                    'tab'     => 'lang:system::settings.text_tab_title_taxation',
                    'type'    => 'switch',
                    'on'      => 'lang:admin::default.text_yes',
                    'off'     => 'lang:admin::default.text_no',
                    'comment' => 'lang:system::settings.help_tax_delivery_charge',
                ],
            ],
        ],
        'rules' => [
            ['order_email.*', 'lang:system::settings.label_order_email', 'required|alpha'],
            ['tax_mode', 'lang:system::settings.label_tax_mode', 'required|integer'],
            ['tax_title', 'lang:system::settings.label_tax_title', 'max:32'],
            ['tax_percentage', 'lang:system::settings.label_tax_percentage', 'required_if:tax_mode,1|numeric'],
            ['tax_menu_price', 'lang:system::settings.label_tax_menu_price', 'numeric'],
            ['tax_delivery_charge', 'lang:system::settings.label_tax_delivery_charge', 'numeric'],
            ['allow_reviews', 'lang:system::settings.label_allow_reviews', 'required|integer'],
            ['approve_reviews', 'lang:system::settings.label_approve_reviews', 'required|integer'],
            ['default_order_status', 'lang:system::settings.label_default_order_status', 'required|integer'],
            ['processing_order_status.*', 'lang:system::settings.label_processing_order_status', 'required|integer'],
            ['completed_order_status.*', 'lang:system::settings.label_completed_order_status', 'required|integer'],
            ['canceled_order_status', 'lang:system::settings.label_canceled_order_status', 'required|integer'],
            ['guest_order', 'lang:system::settings.label_guest_order', 'required|integer'],
            ['location_order', 'lang:system::settings.label_location_order', 'required|integer'],
            ['auto_invoicing', 'lang:system::settings.label_auto_invoicing', 'required|integer'],
            ['invoice_prefix', 'lang:system::settings.label_invoice_prefix'],
        ],
    ],
];

$config['form']['user'] = [
    'label'       => 'lang:system::settings.text_tab_user',
    'description' => 'lang:system::settings.text_tab_desc_user',
    'icon'        => 'fa fa-user',
    'priority'    => 3,
    'url'         => admin_url('settings/edit/user'),
    'form'        => [
        'fields' => [
            'registration_email' => [
                'label'   => 'lang:system::settings.label_registration_email',
                'type'    => 'checkbox',
                'options' => [
                    'customer' => 'lang:system::settings.text_to_customer',
                    'admin'    => 'lang:system::settings.text_to_admin',
                ],
                'comment' => 'lang:system::settings.help_registration_email',
            ],
            'customer_group_id'  => [
                'label'   => 'lang:system::settings.label_customer_group',
                'type'    => 'select',
                'options' => ['Admin\Models\Customer_groups_model', 'getDropdownOptions'],
            ],
        ],
        'rules'  => [
            ['registration_email.*', 'lang:system::settings.label_registration_email', 'required|alpha'],
            ['customer_group_id', 'lang:system::settings.label_customer_group', 'required|integer'],
        ],
    ],
];

$config['form']['media'] = [
    'label'       => 'lang:system::settings.text_tab_media_manager',
    'description' => 'lang:system::settings.text_tab_desc_media_manager',
    'icon'        => 'fa fa-image',
    'priority'    => 4,
    'url'         => admin_url('settings/edit/media'),
    'form'        => [
        'fields' => [
            'image_manager[max_size]'     => [
                'label'   => 'lang:system::settings.label_media_max_size',
                'type'    => 'number',
                'default' => 300,
                'comment' => 'lang:system::settings.help_media_max_size',
            ],
            'image_manager[thumb_width]'  => [
                'label'   => 'lang:system::settings.label_media_thumb_width',
                'type'    => 'number',
                'default' => 320,
                'span'    => 'left',
            ],
            'image_manager[thumb_height]' => [
                'label'   => 'lang:system::settings.label_media_thumb_height',
                'type'    => 'number',
                'default' => 220,
                'span'    => 'right',
            ],
            'image_manager[uploads]'      => [
                'label'   => 'lang:system::settings.label_media_uploads',
                'type'    => 'switch',
                'default' => TRUE,
                'span'    => 'left',
                'comment' => 'lang:system::settings.help_media_upload',
            ],
            'image_manager[new_folder]'   => [
                'label'   => 'lang:system::settings.label_media_new_folder',
                'type'    => 'switch',
                'default' => TRUE,
                'span'    => 'right',
                'comment' => 'lang:system::settings.help_media_new_folder',
            ],
            'image_manager[copy]'         => [
                'label'   => 'lang:system::settings.label_media_copy',
                'type'    => 'switch',
                'default' => TRUE,
                'span'    => 'left',
                'comment' => 'lang:system::settings.help_media_copy',
            ],
            'image_manager[move]'         => [
                'label'   => 'lang:system::settings.label_media_move',
                'type'    => 'switch',
                'default' => TRUE,
                'span'    => 'right',
                'comment' => 'lang:system::settings.help_media_move',
            ],
            'image_manager[rename]'       => [
                'label'   => 'lang:system::settings.label_media_rename',
                'type'    => 'switch',
                'default' => TRUE,
                'span'    => 'left',
                'comment' => 'lang:system::settings.help_media_rename',
            ],
            'image_manager[delete]'       => [
                'label'   => 'lang:system::settings.label_media_delete',
                'type'    => 'switch',
                'default' => TRUE,
                'span'    => 'right',
                'comment' => 'lang:system::settings.help_media_delete',
            ],
        ],
        'rules'  => [
            ['image_manager.max_size', 'lang:system::settings.label_media_max_size', 'required|numeric'],
            ['image_manager.thumb_height', 'lang:system::settings.label_media_thumb_height', 'required|numeric'],
            ['image_manager.thumb_width', 'lang:system::settings.label_media_thumb_width', 'required|numeric'],
            ['image_manager.uploads', 'lang:system::settings.label_media_uploads', 'integer'],
            ['image_manager.new_folder', 'lang:system::settings.label_media_new_folder', 'integer'],
            ['image_manager.copy', 'lang:system::settings.label_media_copy', 'integer'],
            ['image_manager.move', 'lang:system::settings.label_media_move', 'integer'],
            ['image_manager.rename', 'lang:system::settings.label_media_rename', 'integer'],
            ['image_manager.delete', 'lang:system::settings.label_media_delete', 'integer'],
            ['image_manager.transliteration', 'lang:system::settings.label_media_transliteration', 'integer'],
        ],
    ],
];

$config['form']['mail'] = [
    'label'       => 'lang:system::settings.text_tab_mail',
    'description' => 'lang:system::settings.text_tab_desc_mail',
    'icon'        => 'fa fa-envelope',
    'priority'    => 5,
    'url'         => admin_url('settings/edit/mail'),
    'form'        => [
        'fields' => [
            'sender_name'  => [
                'label' => 'lang:system::settings.label_sender_name',
                'type'  => 'text',
                'span'  => 'left',
            ],
            'sender_email' => [
                'label' => 'lang:system::settings.label_sender_email',
                'type'  => 'text',
                'span'  => 'right',
            ],
            'protocol'     => [
                'label'   => 'lang:system::settings.label_protocol',
                'type'    => 'radio',
                'default' => 'sendmail',
                'options' => [
                    'sendmail' => 'lang:system::settings.text_sendmail',
                    'smtp'     => 'lang:system::settings.text_smtp',
                ],
                'span'    => 'left',
            ],
            'smtp_host'    => [
                'label'   => 'lang:system::settings.label_smtp_host',
                'type'    => 'text',
                'span'    => 'right',
                'trigger' => [
                    'action'    => 'show',
                    'field'     => 'protocol',
                    'condition' => 'value[smtp]',
                ],
            ],
            'smtp_port'    => [
                'label'   => 'lang:system::settings.label_smtp_port',
                'type'    => 'text',
                'span'    => 'left',
                'trigger' => [
                    'action'    => 'show',
                    'field'     => 'protocol',
                    'condition' => 'value[smtp]',
                ],
            ],
            'smtp_user'    => [
                'label'   => 'lang:system::settings.label_smtp_user',
                'type'    => 'text',
                'span'    => 'right',
                'trigger' => [
                    'action'    => 'show',
                    'field'     => 'protocol',
                    'condition' => 'value[smtp]',
                ],
            ],
            'smtp_pass'    => [
                'label'   => 'lang:system::settings.label_smtp_pass',
                'type'    => 'text',
                'span'    => 'left',
                'trigger' => [
                    'action'    => 'show',
                    'field'     => 'protocol',
                    'condition' => 'value[smtp]',
                ],
            ],
            'test_email'   => [
                'label' => 'lang:system::settings.label_test_email',
                'type'  => 'partial',
                'path'  => 'settings/test_email_button',
                'span'  => 'right',
            ],
        ],
        'rules'  => [
            ['sender_name', 'lang:system::settings.label_sender_name', 'required'],
            ['sender_email', 'lang:system::settings.label_sender_email', 'required'],
            ['protocol', 'lang:system::settings.label_protocol', 'required'],
            ['smtp_host', 'lang:system::settings.label_smtp_host', 'required_if:protocol,smtp'],
            ['smtp_port', 'lang:system::settings.label_smtp_port', 'required_if:protocol,smtp'],
            ['smtp_user', 'lang:system::settings.label_smtp_user', 'required_if:protocol,smtp'],
            ['smtp_pass', 'lang:system::settings.label_smtp_pass', 'required_if:protocol,smtp'],
        ],
    ],
];

$config['form']['advanced'] = [
    'label'       => 'lang:system::settings.text_tab_server',
    'description' => 'lang:system::settings.text_tab_desc_server',
    'icon'        => 'fa fa-cog',
    'priority'    => 6,
    'url'         => admin_url('settings/edit/advanced'),
    'form'        => [
        'fields' => [
            'maintenance'         => [
                'label' => 'lang:system::settings.text_tab_title_maintenance',
                'type'  => 'section',
            ],
            'maintenance_mode'    => [
                'label'   => 'lang:system::settings.label_maintenance_mode',
                'type'    => 'switch',
                'comment' => 'lang:system::settings.help_maintenance',
            ],
            'maintenance_message' => [
                'label'   => 'lang:system::settings.label_maintenance_message',
                'type'    => 'textarea',
                'default' => 'Site is under maintenance. Please check back later.',
                'trigger' => [
                    'action'    => 'show',
                    'field'     => 'maintenance_mode',
                    'condition' => 'checked',
                ],
            ],

//            'caching'    => [
//                'label' => 'lang:system::settings.text_tab_title_caching',
//                'type'  => 'section',
//            ],
//            'cache_mode' => [
//                'label'   => 'lang:system::settings.label_cache_mode',
//                'type'    => 'switch',
//                'span'    => 'left',
//                'comment' => 'lang:system::settings.help_cache_mode',
//            ],
//            'cache_time' => [
//                'label'   => 'lang:system::settings.label_cache_time',
//                'type'    => 'number',
//                'span'    => 'right',
//                'comment' => 'lang:system::settings.help_cache_time',
//            ],
        ],
        'rules'  => [
            ['maintenance_mode', 'lang:system::settings.label_maintenance_mode', 'required|integer'],
            ['maintenance_message', 'lang:system::settings.label_maintenance_message', 'required'],
//            ['cache_mode', 'lang:system::settings.label_cache_mode', 'required|integer'],
//            ['cache_time', 'lang:system::settings.label_cache_time', 'integer'],
        ],
    ],
];

return $config;